(()=>{
'use strict';
const S=window.SEED_DATA||{}; let state=S; const $=q=>document.querySelector(q);
const fmt=n=>(Number(n||0)/1e8).toLocaleString('ko-KR',{minimumFractionDigits:1,maximumFractionDigits:1});
const pct=n=>Number.isFinite(n)?(n*100).toFixed(1)+'%':'-';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const mgr=v=>{v=String(v||'');return v.includes('백제')&&(v.includes('원주')||v.includes('영남'))?'임인숙':(v.includes('유진약품')||v.includes('아이팜'))?'정직한':'배영훈'};
state.mboByMonth=state.mboByMonth||{}; state.collectionSchedule=state.collectionSchedule||{}; state.customHolidaysByMonth=state.customHolidaysByMonth||{}; state.krHolidays2026=state.krHolidays2026||{};
function months(){const x=new Set();(state.legacyTotals||[]).forEach(r=>x.add(r.month));(state.legacyMonthly||[]).forEach(r=>x.add(r.month));(state.monthlyRecords||[]).forEach(r=>x.add(r.month));(state.dailyRecords||[]).forEach(r=>r.date&&x.add(r.date.slice(0,7)));return [...x].filter(Boolean).sort()}
function am(){return $('#monthFilter').value||months().at(-1)||'2026-08'} function ag(){return $('#managerFilter').value||'ALL'} function av(){return $('#vendorFilter').value||'ALL'}
function ok(r){return (ag()==='ALL'||(r.manager||mgr(r.vendor))===ag())&&(av()==='ALL'||r.vendor===av())}
function prev(m){let [y,mo]=m.split('-').map(Number);mo--;if(!mo){mo=12;y--}return `${y}-${String(mo).padStart(2,'0')}`}
function monthAll(m){const d=(state.monthlyRecords||[]).filter(r=>r.month===m);if(d.length)return d.reduce((a,r)=>a+Number(r.amount||0),0);const t=(state.legacyTotals||[]).find(r=>r.month===m);return t?Number(t.amount||0):(state.legacyMonthly||[]).filter(r=>r.month===m).reduce((a,r)=>a+Number(r.amount||0),0)}
function monthVal(m){const d=(state.monthlyRecords||[]).filter(r=>r.month===m&&ok(r));if(d.length)return d.reduce((a,r)=>a+Number(r.amount||0),0);if(ag()!=='ALL'||av()!=='ALL')return (state.legacyMonthly||[]).filter(r=>r.month===m&&ok(r)).reduce((a,r)=>a+Number(r.amount||0),0);return monthAll(m)}
function daily(m){return (state.dailyRecords||[]).filter(r=>r.date&&r.date.startsWith(m)&&ok(r))}
function latest(m){const d=daily(m).map(r=>r.date).sort();return d.at(-1)||null}
function byDate(m){const o={};daily(m).forEach(r=>o[r.date]=(o[r.date]||0)+Number(r.amount||0));return o}
function businessDates(m){const [y,mo]=m.split('-').map(Number),hol=new Set(Object.keys(state.krHolidays2026||{}).filter(x=>x.startsWith(m)));(state.customHolidaysByMonth[m]||[]).forEach(x=>hol.add(x));const out=[];for(let d=new Date(y,mo-1,1);d.getMonth()===mo-1;d.setDate(d.getDate()+1)){const ds=`${y}-${String(mo).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;if(d.getDay()!=0&&d.getDay()!=6&&!hol.has(ds))out.push(ds)}return out}
function phase(m,date){const b=businessDates(m),s=state.collectionSchedule[m]||{},idx=Math.max(0,b.filter(x=>x<=date).length-1);let a=s.first?Math.max(0,b.filter(x=>x<=s.first).length-1):Math.floor(b.length*.55),c=s.second?Math.max(a+1,b.filter(x=>x<=s.second).length-1):Math.floor(b.length*.75);if(idx<=a)return [0,a?idx/a:0];if(idx<=c)return[1,(idx-a)/Math.max(1,c-a)];return[2,(idx-c)/Math.max(1,b.length-1-c)]}
function eqDate(m,p,r){const b=businessDates(m),s=state.collectionSchedule[m]||{};if(!b.length)return null;let a=s.first?Math.max(0,b.filter(x=>x<=s.first).length-1):Math.floor(b.length*.55),c=s.second?Math.max(a+1,b.filter(x=>x<=s.second).length-1):Math.floor(b.length*.75),i=p===0?Math.round(a*r):p===1?Math.round(a+(c-a)*r):Math.round(c+(b.length-1-c)*r);return b[Math.max(0,Math.min(b.length-1,i))]}
function cumAt(m,d){const o={};(state.dailyRecords||[]).filter(r=>r.date&&r.date.startsWith(m)&&ok(r)).forEach(r=>o[r.date]=(o[r.date]||0)+Number(r.amount||0));return Object.entries(o).filter(([x])=>x<=d).reduce((a,[,v])=>a+v,0)}
function progress(m,d){if(!d)return {v:0,src:'데이터 없음'};const [p,r]=phase(m,d),h=[];months().filter(x=>x<m&&state.collectionSchedule[x]?.first&&state.collectionSchedule[x]?.second).forEach(x=>{const f=monthVal(x),e=eqDate(x,p,r),c=e?cumAt(x,e):0;if(f>0&&c>0&&c/f<1.4)h.push(c/f)});if(h.length>=2)return{v:h.reduce((a,b)=>a+b,0)/h.length,src:`수금 이벤트 정렬 ${h.length}개월`};const b=businessDates(m),i=b.filter(x=>x<=d).length;return{v:Math.max(.01,Math.min(1,i/Math.max(1,b.length))),src:'공휴일 제외 영업일 경과율'}}
function mbo(m){return Number(state.mboByMonth[m]??state.mboTotal??0)}
function target(m){const base=mbo(m);if(ag()==='ALL'&&av()==='ALL')return base;const pm=prev(m),den=monthAll(pm),num=monthVal(pm);return den?base*num/den:base}
function vendors(){const z=new Map();[...(state.legacyMonthly||[]),...(state.monthlyRecords||[]),...(state.dailyRecords||[])].forEach(r=>r.vendor&&z.set(r.vendor,r.manager||mgr(r.vendor)));return [...z.entries()].sort((a,b)=>a[0].localeCompare(b[0],'ko'))}
function init(){const ms=months();$('#monthFilter').innerHTML=ms.map(m=>`<option value="${m}">${m.replace('-','.')}</option>`).join('');$('#monthFilter').value=ms.at(-1)||'2026-08';$('#managerFilter').innerHTML='<option value="ALL">전체</option><option>배영훈</option><option>임인숙</option><option>정직한</option>';vendorOpts();sync();bind();render()}
function vendorOpts(){const cur=av(),g=ag(),vs=vendors().filter(([,m])=>g==='ALL'||m===g);$('#vendorFilter').innerHTML='<option value="ALL">전체</option>'+vs.map(([v])=>`<option value="${esc(v)}">${esc(v)}</option>`).join('');if(vs.some(([v])=>v===cur))$('#vendorFilter').value=cur}
function sync(){const m=am(),s=state.collectionSchedule[m]||{};$('#mboInput').value=(mbo(m)/1e8).toFixed(1);$('#collection1Input').value=s.first||'';$('#collection2Input').value=s.second||'';$('#customHolidayInput').value=(state.customHolidaysByMonth[m]||[]).join(', ')}
function render(){const m=am(),ld=latest(m),cur=monthVal(m),t=target(m),pm=prev(m),pv=monthVal(pm),pr=progress(m,ld),fc=pr.v?cur/pr.v:cur,need=t*pr.v,pur=need?cur/need:0,b=businessDates(m),remain=ld?b.filter(x=>x>ld).length:0,dneed=remain?Math.max(0,t-cur)/remain:0;
$('#heroTitle').textContent=`${m.slice(0,4)}년 ${Number(m.slice(5))}월 매출 진행 현황`;$('#asOfBadge').textContent=ld?`${Number(ld.slice(5,7))}/${Number(ld.slice(8))} 기준`:'월 마감 기준';const s=state.collectionSchedule[m]||{};$('#calendarInfo').textContent=`영업일 ${b.length}일 | 1차 ${s.first||'미입력'} | 2차 ${s.second||'미입력'} | 예측 ${pr.src}`;
const cards=[['현재 누계',fmt(cur)+'억'],['MBO 목표',fmt(t)+'억'],['예상 마감',fmt(fc)+'억'],['순도',pct(pur)],['예측 기준',pct(pr.v)],['MBO 예상 GAP',(fc>=t?'+':'-')+fmt(Math.abs(fc-t))+'억'],['MBO 잔여액',fmt(Math.max(0,t-cur))+'억'],['잔여 영업일 일평균 필요',fmt(dneed)+'억'],['전월 대비',pv?pct(cur/pv-1):'-']];$('#kpiGrid').innerHTML=cards.map(([a,b])=>`<article class="kpi"><span>${a}</span><strong>${b}</strong></article>`).join('');renderV(m,pr.v);renderD(m,t);renderP(m,cur);}
function renderV(m,p){const pm=prev(m),den=monthAll(pm)||1, names=new Set([...(state.legacyMonthly||[]).filter(r=>r.month===m||r.month===pm).map(r=>r.vendor),...(state.monthlyRecords||[]).filter(r=>r.month===m).map(r=>r.vendor)]),rows=[];names.forEach(v=>{const manager=mgr(v);if(ag()!=='ALL'&&manager!==ag()||av()!=='ALL'&&v!==av())return;const c=(state.monthlyRecords||[]).filter(r=>r.month===m&&r.vendor===v).reduce((a,r)=>a+Number(r.amount||0),0),old=(state.legacyMonthly||[]).filter(r=>r.month===pm&&r.vendor===v).reduce((a,r)=>a+Number(r.amount||0),0),sample=(state.legacyMonthly||[]).find(r=>r.vendor===v)||(state.monthlyRecords||[]).find(r=>r.vendor===v)||{};const tar=mbo(m)*old/den;rows.push({v,manager,region:sample.region||'',c,old,fc:p?c/p:c,tar})});rows.sort((a,b)=>b.c-a.c);$('#vendorTable').innerHTML='<thead><tr><th>권역</th><th>업체명</th><th>담당자</th><th>전월</th><th>당월 현수준</th><th>예상 마감</th><th>MBO 배분</th><th>예상 달성률</th></tr></thead><tbody>'+rows.map(r=>`<tr><td>${esc(r.region)}</td><td>${esc(r.v)}</td><td>${r.manager}</td><td>${fmt(r.old)}</td><td>${fmt(r.c)}</td><td>${fmt(r.fc)}</td><td>${fmt(r.tar)}</td><td>${pct(r.tar?r.fc/r.tar:0)}</td></tr>`).join('')+'</tbody>'}
function renderD(m,t){const o=byDate(m),dates=Object.keys(o).sort();let c=0,prevNeed=0;const rows=dates.map(d=>{c+=o[d];const p=progress(m,d).v,n=t*p,dn=Math.max(0,n-prevNeed);prevNeed=n;return[d,o[d],c,dn,n,n?c/n:0]}).reverse();$('#dailyTable').innerHTML='<thead><tr><th>일자</th><th>당일 매출(억)</th><th>누계(억)</th><th>당일 필요(억)</th><th>필요 누계(억)</th><th>순도</th></tr></thead><tbody>'+rows.map(r=>`<tr><td>${r[0]}</td><td>${fmt(r[1])}</td><td>${fmt(r[2])}</td><td>${fmt(r[3])}</td><td>${fmt(r[4])}</td><td>${pct(r[5])}</td></tr>`).join('')+'</tbody>'}
function renderP(m,total){const map=new Map();(state.monthlyRecords||[]).filter(r=>r.month===m&&ok(r)).forEach(r=>map.set(r.productGroup||'미분류',(map.get(r.productGroup||'미분류')||0)+Number(r.amount||0)));const a=[...map.entries()].sort((x,y)=>y[1]-x[1]).slice(0,50);$('#productTable').innerHTML='<thead><tr><th>제품군</th><th>매출(억)</th><th>비중</th></tr></thead><tbody>'+a.map(r=>`<tr><td>${esc(r[0])}</td><td>${fmt(r[1])}</td><td>${pct(r[1]/Math.max(1,total))}</td></tr>`).join('')+'</tbody>'}
function bind(){if(window.__bound)return;window.__bound=1;$('#managerFilter').addEventListener('change',()=>{vendorOpts();render()});$('#vendorFilter').addEventListener('change',render);$('#monthFilter').addEventListener('change',()=>{sync();render()});$('#mboInput').addEventListener('change',e=>{state.mboByMonth[am()]=Number(e.target.value||0)*1e8;render()});$('#collection1Input').addEventListener('change',e=>{state.collectionSchedule[am()]=state.collectionSchedule[am()]||{};state.collectionSchedule[am()].first=e.target.value||null;render()});$('#collection2Input').addEventListener('change',e=>{state.collectionSchedule[am()]=state.collectionSchedule[am()]||{};state.collectionSchedule[am()].second=e.target.value||null;render()});$('#customHolidayInput').addEventListener('change',e=>{state.customHolidaysByMonth[am()]=String(e.target.value||'').split(/[,;\s]+/).filter(Boolean).map(x=>x.length<=5?`${am()}-${x.split(/[\/.\-]/).pop().padStart(2,'0')}`:x);render()});$('#resetBtn').addEventListener('click',()=>{location.reload()});$('#monthlyUpload').addEventListener('change',e=>upload(e,'monthly'));$('#dailyUpload').addEventListener('change',e=>upload(e,'daily'))}
async function upload(e,type){if(!window.XLSX){$('#status').textContent='Excel 업로드 기능 로딩 중입니다. 잠시 후 다시 선택해 주세요.';return}const f=e.target.files[0];if(!f)return;const wb=XLSX.read(await f.arrayBuffer(),{type:'array',cellDates:true}),ws=wb.Sheets[wb.SheetNames[0]],rows=XLSX.utils.sheet_to_json(ws,{defval:null,raw:true});if(type==='daily'){const mon=new Set(rows.map(r=>parseD(r['일자'])?.slice(0,7)).filter(Boolean));state.dailyRecords=(state.dailyRecords||[]).filter(r=>!mon.has(r.date.slice(0,7)));rows.forEach(r=>{const d=parseD(r['일자']);if(d&&r['판매처명'])state.dailyRecords.push({date:d,vendor:String(r['판매처명']),manager:mgr(r['판매처명']),region:String(r['지역명']||''),productGroup:String(r['제품계층구조2 명']||'미분류'),material:String(r['자재명']||'미분류'),amount:Number(r['실매출액']||0)})})}else{const mon=new Set(rows.map(r=>String(r['년월']||'').replace('.','-')).filter(Boolean));state.monthlyRecords=(state.monthlyRecords||[]).filter(r=>!mon.has(r.month));rows.forEach(r=>{if(r['년월']&&r['판매처명'])state.monthlyRecords.push({month:String(r['년월']).replace('.','-'),vendor:String(r['판매처명']),manager:mgr(r['판매처명']),region:String(r['지역명']||''),productGroup:String(r['제품계층구조2 명']||'미분류'),material:String(r['자재명']||'미분류'),amount:Number(r['실매출액']||0)})})}init();$('#status').textContent=`${f.name} 반영 완료`}
function parseD(v){if(v instanceof Date)return v.toISOString().slice(0,10);const m=String(v||'').match(/(20\d{2})[.\/-](\d{1,2})[.\/-](\d{1,2})/);return m?`${m[1]}-${m[2].padStart(2,'0')}-${m[3].padStart(2,'0')}`:null}
try{init()}catch(e){console.error(e);const s=$('#status');if(s)s.textContent='대시보드 초기화 오류: '+e.message}
})();
