(function(){
'use strict';
var state=window.SEED_DATA||{};
var STORAGE='sales_forecast_v11_settings';
function el(id){return document.getElementById(id)}
function num(v){return Number(v||0)}
function fmt(v){return (num(v)/100000000).toLocaleString('ko-KR',{minimumFractionDigits:1,maximumFractionDigits:1})}
function pct(v){return isFinite(v)?(v*100).toFixed(1)+'%':'-'}
function esc(s){return String(s==null?'':s).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}
function manager(v){v=String(v||'');if(v.indexOf('백제')>=0&&(v.indexOf('원주')>=0||v.indexOf('영남')>=0))return '임인숙';if(v.indexOf('유진약품')>=0||v.indexOf('아이팜')>=0)return '정직한';return '배영훈'}
state.mboByMonth={};state.customHolidaysByMonth=state.customHolidaysByMonth||{};state.collectionSchedule=state.collectionSchedule||{};state.krHolidays2026=state.krHolidays2026||{};
try{var sv=JSON.parse(localStorage.getItem(STORAGE)||'{}');state.mboByMonth=sv.mboByMonth||{};state.collectionSchedule=Object.assign(state.collectionSchedule,sv.collectionSchedule||{});state.customHolidaysByMonth=sv.customHolidaysByMonth||state.customHolidaysByMonth||{};}catch(e){}
function save(){try{localStorage.setItem(STORAGE,JSON.stringify({mboByMonth:state.mboByMonth,collectionSchedule:state.collectionSchedule,customHolidaysByMonth:state.customHolidaysByMonth}))}catch(e){}}
function months(){var s={};(state.legacyTotals||[]).forEach(function(r){s[r.month]=1});(state.legacyMonthly||[]).forEach(function(r){s[r.month]=1});(state.monthlyRecords||[]).forEach(function(r){s[r.month]=1});(state.dailyRecords||[]).forEach(function(r){if(r.date)s[r.date.slice(0,7)]=1});return Object.keys(s).sort()}
function activeMonth(){return el('monthFilter').value||months()[months().length-1]||'2026-08'}
function activeManager(){return el('managerFilter').value||'ALL'}
function activeVendor(){return el('vendorFilter').value||'ALL'}
function match(r){return (activeManager()==='ALL'||(r.manager||manager(r.vendor))===activeManager())&&(activeVendor()==='ALL'||r.vendor===activeVendor())}
function prevMonth(m){var p=m.split('-'),y=+p[0],mo=+p[1]-1;if(mo===0){mo=12;y--}return y+'-'+String(mo).padStart(2,'0')}
function monthAll(m){var d=(state.monthlyRecords||[]).filter(function(r){return r.month===m});if(d.length)return d.reduce(function(a,r){return a+num(r.amount)},0);var t=(state.legacyTotals||[]).filter(function(r){return r.month===m})[0];if(t)return num(t.amount);return (state.legacyMonthly||[]).filter(function(r){return r.month===m}).reduce(function(a,r){return a+num(r.amount)},0)}
function monthValue(m){var d=(state.monthlyRecords||[]).filter(function(r){return r.month===m&&match(r)});if(d.length)return d.reduce(function(a,r){return a+num(r.amount)},0);if(activeManager()!=='ALL'||activeVendor()!=='ALL')return (state.legacyMonthly||[]).filter(function(r){return r.month===m&&match(r)}).reduce(function(a,r){return a+num(r.amount)},0);return monthAll(m)}
function overallByDate(m){var o={};(state.dailyRecords||[]).forEach(function(r){if(r.date&&r.date.slice(0,7)===m)o[r.date]=(o[r.date]||0)+num(r.amount)});return o}
function latestDate(m){var a=Object.keys(overallByDate(m)).sort();return a.length?a[a.length-1]:null}
function businessDates(m){var p=m.split('-'),y=+p[0],mo=+p[1],hol={};Object.keys(state.krHolidays2026||{}).forEach(function(d){if(d.slice(0,7)===m)hol[d]=1});(state.customHolidaysByMonth[m]||[]).forEach(function(d){hol[d]=1});var out=[];for(var d=new Date(y,mo-1,1);d.getMonth()===mo-1;d.setDate(d.getDate()+1)){var ds=y+'-'+String(mo).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0');if(d.getDay()!==0&&d.getDay()!==6&&!hol[ds])out.push(ds)}return out}
function phase(m,date){var b=businessDates(m),s=state.collectionSchedule[m]||{},idx=Math.max(0,b.filter(function(x){return x<=date}).length-1);var a=s.first?Math.max(0,b.filter(function(x){return x<=s.first}).length-1):Math.floor(b.length*.55);var c=s.second?Math.max(a+1,b.filter(function(x){return x<=s.second}).length-1):Math.floor(b.length*.75);if(idx<=a)return[0,a?idx/a:0];if(idx<=c)return[1,(idx-a)/Math.max(1,c-a)];return[2,(idx-c)/Math.max(1,b.length-1-c)]}
function eqDate(m,p,r){var b=businessDates(m),s=state.collectionSchedule[m]||{};if(!b.length)return null;var a=s.first?Math.max(0,b.filter(function(x){return x<=s.first}).length-1):Math.floor(b.length*.55);var c=s.second?Math.max(a+1,b.filter(function(x){return x<=s.second}).length-1):Math.floor(b.length*.75);var i=p===0?Math.round(a*r):p===1?Math.round(a+(c-a)*r):Math.round(c+(b.length-1-c)*r);i=Math.max(0,Math.min(b.length-1,i));return b[i]}
function overallCum(m,date){var o=overallByDate(m),sum=0;Object.keys(o).forEach(function(d){if(d<=date)sum+=o[d]});return sum}
function progress(m,date){if(!date)return{v:0,src:'데이터 없음'};var ph=phase(m,date),hist=[];months().filter(function(x){var s=state.collectionSchedule[x]||{};return x<m&&s.first&&s.second}).forEach(function(x){var final=monthAll(x),ed=eqDate(x,ph[0],ph[1]),cum=ed?overallCum(x,ed):0;if(final>0&&cum>0&&cum/final<1.4)hist.push(cum/final)});if(hist.length>=2)return{v:hist.reduce(function(a,b){return a+b},0)/hist.length,src:'수금 이벤트 정렬 '+hist.length+'개월'};var b=businessDates(m),idx=b.filter(function(x){return x<=date}).length;return{v:Math.max(.01,Math.min(1,idx/Math.max(1,b.length))),src:'공휴일 제외 영업일 경과율'}}
function mbo(m){var v=state.mboByMonth[m];return v==null?null:num(v)}
function targetForFilter(m){var base=mbo(m);if(base==null)return null;if(activeManager()==='ALL'&&activeVendor()==='ALL')return base;var pm=prevMonth(m),den=monthAll(pm),n=monthValue(pm);return den>0?base*n/den:base}
function syncVendor(){var map={};[].concat(state.legacyMonthly||[],state.monthlyRecords||[]).forEach(function(r){if(r.vendor)map[r.vendor]=r.manager||manager(r.vendor)});var g=activeManager(),cur=activeVendor(),vs=Object.keys(map).filter(function(v){return g==='ALL'||map[v]===g}).sort();el('vendorFilter').innerHTML='<option value="ALL">전체</option>'+vs.map(function(v){return '<option value="'+esc(v)+'">'+esc(v)+'</option>'}).join('');if(vs.indexOf(cur)>=0)el('vendorFilter').value=cur}
function syncInputs(){var m=activeMonth(),s=state.collectionSchedule[m]||{},v=mbo(m);el('mboInput').value=v==null?'':(v/100000000).toFixed(1);el('collection1Input').value=s.first||'';el('collection2Input').value=s.second||'';el('customHolidayInput').value=(state.customHolidaysByMonth[m]||[]).join(', ')}
function card(label,value,sub,cls){return '<article class="kpi '+(cls||'')+'"><div class="label">'+label+'</div><div class="value">'+value+'</div><div class="sub">'+(sub||'')+'</div></article>'}
function render(){var m=activeMonth(),ld=latestDate(m),cur=monthValue(m),pr=progress(m,ld),forecast=pr.v?cur/pr.v:cur,t=targetForFilter(m),pm=prevMonth(m),pv=monthValue(pm),b=businessDates(m),remain=ld?b.filter(function(d){return d>ld}).length:0;var need=t==null?null:t*pr.v;var purity=need?cur/need:null;var gap=t==null?null:forecast-t;var left=t==null?null:Math.max(0,t-cur);var dneed=t==null?null:(remain?left/remain:0);var s=state.collectionSchedule[m]||{};
el('heroTitle').textContent=m.slice(0,4)+'년 '+Number(m.slice(5))+'월 매출 진행 현황';el('asOfBadge').textContent=ld?(Number(ld.slice(5,7))+'/'+Number(ld.slice(8))+' 기준'):'월 마감 기준';el('calendarInfo').textContent='영업일 '+b.length+'일 | 1차 '+(s.first||'미입력')+' | 2차 '+(s.second||'미입력')+' | '+pr.src;
var c=[];c.push(card('현재 누계',fmt(cur)+'억',ld||'','good'));c.push(card('MBO 목표',t==null?'입력 필요':fmt(t)+'억','월별 직접 입력','warn'));c.push(card('예상 마감',fmt(forecast)+'억','매출 진행 패턴 기반','good'));c.push(card('순도',t==null?'MBO 입력 필요':pct(purity),'실제 누계 ÷ 필요 누계',purity!=null&&purity>=1?'good':'warn'));c.push(card('예측 진행률',pct(pr.v),pr.src,'info'));c.push(card('MBO 예상 GAP',t==null?'MBO 입력 필요':((gap>=0?'+':'-')+fmt(Math.abs(gap))+'억'),'예상마감 - MBO',gap!=null&&gap>=0?'good':'bad'));c.push(card('MBO 잔여액',t==null?'MBO 입력 필요':fmt(left)+'억','현재누계 기준',''));c.push(card('잔여 영업일 일평균 필요',t==null?'MBO 입력 필요':fmt(dneed)+'억',remain+'영업일 잔여',''));c.push(card('전월 대비',pv?pct(cur/pv-1):'-','전월 마감 대비',''));el('kpiGrid').innerHTML=c.join('');renderVendor(m,pr.v);renderDaily(m,t);renderProducts(m,cur);el('status').textContent='데이터 정상 로드 · MBO는 기준월별 직접 입력값을 사용합니다.'}
function renderVendor(m,p){var pm=prevMonth(m),den=monthAll(pm)||1,names={};(state.legacyMonthly||[]).filter(function(r){return r.month===m||r.month===pm}).forEach(function(r){names[r.vendor]=1});(state.monthlyRecords||[]).filter(function(r){return r.month===m}).forEach(function(r){names[r.vendor]=1});var rows=[];Object.keys(names).forEach(function(v){var mg=manager(v);if(activeManager()!=='ALL'&&mg!==activeManager())return;if(activeVendor()!=='ALL'&&v!==activeVendor())return;var current=(state.monthlyRecords||[]).filter(function(r){return r.month===m&&r.vendor===v}).reduce(function(a,r){return a+num(r.amount)},0);var old=(state.legacyMonthly||[]).filter(function(r){return r.month===pm&&r.vendor===v}).reduce(function(a,r){return a+num(r.amount)},0);var sample=(state.monthlyRecords||[]).filter(function(r){return r.vendor===v})[0]||(state.legacyMonthly||[]).filter(function(r){return r.vendor===v})[0]||{};var totalMbo=mbo(m),tar=totalMbo==null?null:totalMbo*old/den;rows.push({v:v,mg:mg,region:sample.region||'',current:current,old:old,fc:p?current/p:current,tar:tar})});rows.sort(function(a,b){return b.current-a.current});el('vendorTable').innerHTML='<thead><tr><th>권역</th><th>업체명</th><th>담당자</th><th>전월</th><th>당월 현수준</th><th>예상 마감</th><th>MBO 배분</th><th>예상 달성률</th></tr></thead><tbody>'+rows.map(function(r){return '<tr><td>'+esc(r.region)+'</td><td>'+esc(r.v)+'</td><td>'+r.mg+'</td><td>'+fmt(r.old)+'</td><td>'+fmt(r.current)+'</td><td>'+fmt(r.fc)+'</td><td>'+(r.tar==null?'-':fmt(r.tar))+'</td><td>'+(r.tar?pct(r.fc/r.tar):'-')+'</td></tr>'}).join('')+'</tbody>'}
function renderDaily(m,t){if(activeManager()!=='ALL'||activeVendor()!=='ALL'){el('dailyTable').innerHTML='<tbody><tr><td colspan="6">담당자/업체 선택 시 일자별 원본 업로드 후 개별 순도 분석이 가능합니다. 예상마감은 전체 수금 이벤트 패턴을 적용합니다.</td></tr></tbody>';return}var o=overallByDate(m),dates=Object.keys(o).sort(),cum=0,prevNeed=0,rows=[];dates.forEach(function(d){cum+=o[d];var p=progress(m,d).v,n=t==null?null:t*p,dn=n==null?null:Math.max(0,n-prevNeed);if(n!=null)prevNeed=n;rows.push([d,o[d],cum,dn,n,n?cum/n:null])});rows.reverse();el('dailyTable').innerHTML='<thead><tr><th>일자</th><th>당일 매출(억)</th><th>누계(억)</th><th>당일 필요(억)</th><th>필요 누계(억)</th><th>순도</th></tr></thead><tbody>'+rows.map(function(r){return '<tr><td>'+r[0]+'</td><td>'+fmt(r[1])+'</td><td>'+fmt(r[2])+'</td><td>'+(r[3]==null?'-':fmt(r[3]))+'</td><td>'+(r[4]==null?'-':fmt(r[4]))+'</td><td>'+(r[5]==null?'-':pct(r[5]))+'</td></tr>'}).join('')+'</tbody>'}
function renderProducts(m,total){var map={};(state.monthlyRecords||[]).filter(function(r){return r.month===m&&match(r)}).forEach(function(r){var k=r.productGroup||'미분류';map[k]=(map[k]||0)+num(r.amount)});var a=Object.keys(map).map(function(k){return[k,map[k]]}).sort(function(x,y){return y[1]-x[1]}).slice(0,50);el('productTable').innerHTML='<thead><tr><th>제품군</th><th>매출(억)</th><th>비중</th></tr></thead><tbody>'+a.map(function(r){return '<tr><td>'+esc(r[0])+'</td><td>'+fmt(r[1])+'</td><td>'+pct(r[1]/Math.max(1,total))+'</td></tr>'}).join('')+'</tbody>'}
function parseDate(v){if(v instanceof Date)return v.toISOString().slice(0,10);var m=String(v||'').match(/(20\d{2})[.\/-](\d{1,2})[.\/-](\d{1,2})/);return m?m[1]+'-'+m[2].padStart(2,'0')+'-'+m[3].padStart(2,'0'):null}
async function upload(input,type){if(!window.XLSX){el('status').textContent='Excel 모듈이 아직 로드되지 않았습니다. 잠시 후 다시 선택해 주세요.';input.value='';return}var f=input.files&&input.files[0];if(!f)return;try{var wb=XLSX.read(await f.arrayBuffer(),{type:'array',cellDates:true}),ws=wb.Sheets[wb.SheetNames[0]],rows=XLSX.utils.sheet_to_json(ws,{defval:null,raw:true});if(type==='daily'){var mons={};rows.forEach(function(r){var d=parseDate(r['일자']);if(d)mons[d.slice(0,7)]=1});state.dailyRecords=(state.dailyRecords||[]).filter(function(r){return !mons[r.date.slice(0,7)]});rows.forEach(function(r){var d=parseDate(r['일자']),v=r['판매처명'];if(d&&v)state.dailyRecords.push({date:d,vendor:String(v),manager:manager(v),region:String(r['지역명']||''),productGroup:String(r['제품계층구조2 명']||'미분류'),material:String(r['자재명']||'미분류'),amount:num(r['실매출액'])})})}else{var mons2={};rows.forEach(function(r){var s=String(r['년월']||'').replace('.','-'),m=s.match(/(20\d{2})-(\d{1,2})/);if(m)mons2[m[1]+'-'+m[2].padStart(2,'0')]=1});state.monthlyRecords=(state.monthlyRecords||[]).filter(function(r){return !mons2[r.month]});rows.forEach(function(r){var s=String(r['년월']||'').replace('.','-'),mm=s.match(/(20\d{2})-(\d{1,2})/),v=r['판매처명'];if(mm&&v)state.monthlyRecords.push({month:mm[1]+'-'+mm[2].padStart(2,'0'),vendor:String(v),manager:manager(v),region:String(r['지역명']||''),productGroup:String(r['제품계층구조2 명']||'미분류'),material:String(r['자재명']||'미분류'),amount:num(r['실매출액'])})})}initMonths();syncVendor();syncInputs();render();el('status').textContent=f.name+' 반영 완료'}catch(e){console.error(e);el('status').textContent='업로드 오류: '+e.message}}
function initMonths(){var ms=months(),cur=el('monthFilter').value;el('monthFilter').innerHTML=ms.map(function(m){return '<option value="'+m+'">'+m.replace('-','.')+'</option>'}).join('');el('monthFilter').value=ms.indexOf(cur)>=0?cur:ms[ms.length-1]}
function bind(){el('managerFilter').addEventListener('change',function(){syncVendor();render()});el('vendorFilter').addEventListener('change',render);el('monthFilter').addEventListener('change',function(){syncInputs();render()});el('mboInput').addEventListener('input',function(){var v=this.value.trim();if(v==='')delete state.mboByMonth[activeMonth()];else state.mboByMonth[activeMonth()]=Number(v)*100000000;save();render()});el('collection1Input').addEventListener('change',function(){state.collectionSchedule[activeMonth()]=state.collectionSchedule[activeMonth()]||{};state.collectionSchedule[activeMonth()].first=this.value||null;save();render()});el('collection2Input').addEventListener('change',function(){state.collectionSchedule[activeMonth()]=state.collectionSchedule[activeMonth()]||{};state.collectionSchedule[activeMonth()].second=this.value||null;save();render()});el('customHolidayInput').addEventListener('change',function(){state.customHolidaysByMonth[activeMonth()]=String(this.value||'').split(/[,;\s]+/).filter(Boolean);save();render()});el('monthlyUpload').addEventListener('change',function(){upload(this,'monthly')});el('dailyUpload').addEventListener('change',function(){upload(this,'daily')})}
function init(){initMonths();el('managerFilter').innerHTML='<option value="ALL">전체</option><option>배영훈</option><option>임인숙</option><option>정직한</option>';syncVendor();syncInputs();bind();render()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',function(){try{init()}catch(e){console.error(e);el('status').textContent='초기화 오류: '+e.message}});else{try{init()}catch(e){console.error(e);el('status').textContent='초기화 오류: '+e.message}}
})();