(()=>{'use strict';
const STORE='sales_forecast_v16',CLOSE_KEY='sales_forecast_vendor_closed_v66',API='https://api.github.com/repos/yhbae106/Sales_Forecast/contents/shared-data/sales-history.json?ref=main';
const $=s=>document.querySelector(s),status=m=>{const e=$('#status');if(e)e.textContent=m};
const setBrand=()=>{const e=$('.eyebrow'),h=$('.top h1');if(e)e.textContent='SCM SALES Forecast CONTROL TOWER';if(h)h.textContent='종합도매 매출 · MBO 운영 대시보드';document.title='SCM SALES Forecast CONTROL TOWER | 종합도매 매출 · MBO 운영 대시보드'};
const short=d=>d?`${Number(d.slice(5,7))}/${Number(d.slice(8))}까지 반영 완료`:'공용 데이터 대기';
const load=src=>new Promise((resolve,reject)=>{const s=document.createElement('script');s.src=src;s.async=false;s.onload=resolve;s.onerror=()=>reject(new Error(src+' 로드 실패'));document.body.appendChild(s)});
const waitSeed=(max=4500)=>new Promise(resolve=>{if(window.SEED_DATA?.dailyRecords?.length)return resolve(true);const started=Date.now(),id=setInterval(()=>{if(window.SEED_DATA?.dailyRecords?.length||Date.now()-started>=max){clearInterval(id);resolve(!!window.SEED_DATA?.dailyRecords?.length)}},40)});
async function readSharedApi(){const r=await fetch(API+'&t='+Date.now(),{headers:{Accept:'application/vnd.github.raw+json','X-GitHub-Api-Version':'2022-11-28'},cache:'no-store'});if(!r.ok)throw new Error('공용 데이터 HTTP '+r.status);return r.json()}
function lastDate(shared){const a=(shared.sourceFiles||[]).map(x=>x.lastDate||x.date).filter(Boolean),b=(shared.uploads||[]).map(x=>x.d||x.date).filter(Boolean);return [...a,...b].sort().at(-1)||''}
async function hydrate(){const shared=await readSharedApi();const up=Array.isArray(shared.uploads)?shared.uploads:[];window.__SF_SHARED_UPLOADS=up;window.__sfSharedMeta=shared;window.__sfReadShared=window.__sfReadShared||readSharedApi;let local={};try{local=JSON.parse(localStorage.getItem(STORE)||localStorage.getItem('sales_forecast_v15')||'{}')}catch(e){}let localClosed={};try{localClosed=JSON.parse(localStorage.getItem(CLOSE_KEY)||'{}')}catch(e){}const lean={mbo:shared.mbo&&Object.keys(shared.mbo).length?shared.mbo:(local.mbo||{}),gmbo:shared.gmbo&&Object.keys(shared.gmbo).length?shared.gmbo:(local.gmbo||local.groupMbo||{}),sched:shared.sched&&Object.keys(shared.sched).length?shared.sched:(local.sched||{}),up};const sharedClosed=shared.closedVendors&&typeof shared.closedVendors==='object'?shared.closedVendors:null;window.__SF_BOOTSTRAP_LEAN=lean;window.__SF_SHARED_CLOSED=sharedClosed||localClosed;try{localStorage.setItem(STORE,JSON.stringify(lean));localStorage.setItem(CLOSE_KEY,JSON.stringify(window.__SF_SHARED_CLOSED));window.__SF_SHARED_STORAGE_FAILED=false}catch(e){window.__SF_SHARED_STORAGE_FAILED=true}const last=lastDate(shared);window.__SF_SHARED_LAST=last;status(short(last));return last}
function installMemoryStore(){if(!window.__SF_SHARED_STORAGE_FAILED)return()=>{};const orig=Storage.prototype.getItem;Storage.prototype.getItem=function(k){if(this===localStorage&&(k===STORE||k==='sales_forecast_v15'))return JSON.stringify(window.__SF_BOOTSTRAP_LEAN||{});if(this===localStorage&&k===CLOSE_KEY)return JSON.stringify(window.__SF_SHARED_CLOSED||{});return orig.call(this,k)};return()=>{Storage.prototype.getItem=orig}}
async function cleanupLegacyCachesOnce(){try{if(sessionStorage.getItem('sf_cache_cleanup_v77')==='1')return;if('serviceWorker'in navigator)(await navigator.serviceWorker.getRegistrations()).forEach(r=>r.unregister());if(window.caches){for(const k of await caches.keys())if(k.startsWith('sales-forecast-static-'))await caches.delete(k)}sessionStorage.setItem('sf_cache_cleanup_v77','1')}catch(e){}}
(async()=>{setBrand();await cleanupLegacyCachesOnce();try{await hydrate()}catch(e){status('공용 데이터 연결 오류: '+e.message)}const restoreStore=installMemoryStore();await load('v16-legacy.js?v=77');await waitSeed();restoreStore();await load('shared-v31.js?v=77');await load('master-upload-v34.js?v=77');await load('kpi-layout-v37.js?v=77');await load('upper-history-v39.js?v=77');await load('vendor-mbo-gap-v43.js?v=77');await load('vendor-close-ui-v67.js?v=77');setBrand();if(window.__SF_SHARED_LAST)status(short(window.__SF_SHARED_LAST));window.__sfCoreReady=true;window.dispatchEvent(new Event('sf-core-ready'))})().catch(e=>status('대시보드 로딩 오류: '+e.message));
})();