(()=>{'use strict';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],N=v=>Number(v||0),W=v=>(N(v)/1e8).toLocaleString('ko-KR',{minimumFractionDigits:1,maximumFractionDigits:1}),P=v=>Number.isFinite(v)?(v*100).toFixed(1)+'%':'-',X=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const KEY=['백제약품영등포지점','백제약품(주)영남본부','대전백제약품','백제약품(주)원주지점','(주)인천약품','(주)복산나이스','유진약품(주)','아이팜코리아(주)'];
let upperVendor='',lowerVendor='',sortKey='sales',sortDir='desc',analysisSort='current',analysisDir='desc',lastSig='';
function style(){if($('#decoupleV22Style'))return;const s=document.createElement('style');s.id='decoupleV22Style';s.textContent=`
.scope-badge{display:inline-flex;align-items:center;gap:6px;margin-left:6px;padding:5px 10px;border-radius:999px;background:#0b3048;border:1px solid #3a7898;color:#91e0f2;font-size:11px;font-weight:850}.scope-badge strong{color:#fff}.scope-tools{display:grid;grid-template-columns:1.5fr .9fr .8fr;gap:8px;margin:11px 0}.scope-tools label{font-size:11px;color:#91a9c1;font-weight:800}.scope-tools select{width:100%;margin-top:5px;padding:9px;border-radius:9px;border:1px solid #31506b;background:#071522;color:#eef6ff}.section-callout{margin:8px 0 12px;padding:11px 13px;border-left:4px solid #4fd1c5;border-radius:9px;background:#082338;color:#d9edf8;font-size:12px}.section-callout strong{color:#fff}.overview-row{cursor:pointer!important}.overview-row td{background:linear-gradient(90deg,#164e6e,#0e334d)!important;border-top:2px solid #4fd1c5!important;border-bottom:2px solid #4fd1c5!important;font-weight:900!important}.overview-row:hover td{background:linear-gradient(90deg,#1d668b,#154760)!important}.overview-cta{display:inline-flex;align-items:center;gap:7px;padding:7px 12px;border-radius:999px;background:#4fd1c5;color:#062033;font-weight:950;font-size:11px;box-shadow:0 0 0 3px rgba(79,209,197,.13)}.overview-row td:first-child{color:#9df4e7}.analysis-sort{cursor:pointer;user-select:none}.analysis-sort:hover{color:#4fd1c5!important;background:#173752!important}.analysis-sort.active{color:#4fd1c5!important}.group-scope-title{display:flex;align-items:center;gap:6px;flex-wrap:wrap}.selected td{background:rgba(79,209,197,.08)!important}@media(max-width:720px){.scope-tools{grid-template-columns:1fr}}`;document.head.appendChild(s)}
function storedUploads(){try{const z=JSON.parse(localStorage.getItem('sales_forecast_v16')||localStorage.getItem('sales_forecast_v15')||'{}');return z.up||z.uploadRows||z.uploads||[]}catch(e){return[]}}
function seedRows(){const raw=window.SEED_DATA?.dailyRecords||[];return raw.map(r=>({d:r.date,v:r.vendor||'',g:r.productGroup||'미분류',m:r.material||'미분류',a:N(r.amount)}))}
function all(){const up=storedUploads(),rep=new Set(up.map(r=>r.d||r.date)),seed=seedRows().filter(r=>!rep.has(r.d));return seed.concat(up.map(r=>({d:r.d||r.date,v:r.v||r.vendor||'',g:r.g||r.productGroup||'미분류',m:r.m||r.material||'미분류',a:N(r.a??r.amount)})))}
const month=()=>$('#month')?.value||'';function monthRows(m=month()){return all().filter(r=>r.d?.slice(0,7)===m)}
function scoped(v,m=month()){const r=monthRows(m);if(!v)return r;if(v==='권역 외 업체')return r.filter(x=>!KEY.includes(x.v));if(v==='백제약품 전체 합계')return r.filter(x=>KEY.slice(0,4).includes(x.v));return r.filter(x=>x.v===v)}
function totalCurrent(){const c=$$('#cards .card').find(x=>(x.querySelector('.label')?.textContent||'').trim()==='현재 누계');const txt=c?.querySelector('.value')?.textContent||'';const n=Number((txt.match(/-?[\d,.]+/)||['0'])[0].replace(/,/g,''));return n||monthRows().reduce((s,r)=>s+N(r.a),0)/1e8}
function setGroupScopeLabel(){const sec=$('#groupTable')?.closest('section.panel'),h=sec?.querySelector('.head h3'),p=sec?.querySelector('.head p');if(h)h.innerHTML=`<span class="group-scope-title">제품군 현황 <span class="scope-badge">현재 기준: <strong>${X(upperVendor||'전체 업체')}</strong></span></span>`;if(p)p.textContent=upperVendor?`${upperVendor}의 제품군 매출 현황입니다.`:'전체 업체의 제품군 매출 현황입니다.'}
function renderUpperGroup(){const t=$('#groupTable');if(!t)return;const rs=scoped(upperVendor),mp={};rs.forEach(r=>mp[r.g]=(mp[r.g]||0)+N(r.a));const total=rs.reduce((s,r)=>s+N(r.a),0);t.innerHTML='<thead><tr><th>제품군</th><th>매출(억)</th><th>비중</th></tr></thead><tbody>'+Object.entries(mp).sort((a,b)=>b[1]-a[1]).map(([g,a])=>`<tr><td>${X(g)}</td><td>${W(a)}</td><td>${P(a/Math.max(1,total))}</td></tr>`).join('')+'</tbody>';setGroupScopeLabel()}
function ensureOverviewRow(){const body=$('#vendorTable tbody');if(!body)return;body.querySelectorAll('.v22-overview').forEach(r=>r.remove());const grand=totalCurrent();const row=document.createElement('tr');row.className='v22-overview overview-row';row.tabIndex=0;row.setAttribute('role','button');row.setAttribute('aria-label','전체 현황 보기');row.title='클릭하면 오른쪽 제품군 현황을 전체 업체 기준으로 되돌립니다.';row.innerHTML=`<td>총합계</td><td><span class="overview-cta">↺ 전체 현황 보기</span></td><td>${grand.toFixed(1)}</td><td>100.0%</td>`;const go=()=>{upperVendor='';renderUpperGroup();$$('#vendorTable tr').forEach(r=>r.classList.remove('selected'));row.classList.add('selected');const st=$('#status');if(st)st.textContent='전체 업체 기준 제품군 현황으로 전환했습니다.'};row.onclick=go;row.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();go()}};body.appendChild(row)}
function overrideUpperClicks(){$$('#vendorTable tr[data-v]').forEach(r=>{const v=r.dataset.v;if(!v)return;r.onclick=e=>{e.preventDefault();e.stopPropagation();upperVendor=v;renderUpperGroup();$$('#vendorTable tr').forEach(x=>x.classList.remove('selected'));r.classList.add('selected')}})}
function sortEntries(mp){return Object.entries(mp).sort((a,b)=>sortKey==='name'?(sortDir==='asc'?1:-1)*a[0].localeCompare(b[0],'ko'):(sortDir==='asc'?1:-1)*(a[1]-b[1]))}
function activeMode(){return $('.tabs .tab.active')?.dataset.tab==='groups'?'groups':'materials'}
function renderLowerDetail(){const t=$('#detailTable');if(!t)return;const rs=scoped(lowerVendor),tab=$('.tabs .tab.active')?.dataset.tab||'materials',mp={};rs.forEach(r=>{const q=tab==='groups'?r.g:tab==='vendors'?r.v:r.m;mp[q]=(mp[q]||0)+N(r.a)});const total=rs.reduce((s,r)=>s+N(r.a),0);t.innerHTML='<thead><tr><th>'+(tab==='groups'?'제품군':tab==='vendors'?'업체':'품목(자재명)')+'</th><th>매출(억)</th><th>비중</th></tr></thead><tbody>'+sortEntries(mp).map(([q,a])=>`<tr><td>${X(q)}</td><td>${W(a)}</td><td>${P(a/Math.max(1,total))}</td></tr>`).join('')+'</tbody>';$('#detailTitle').textContent='전체 상세 현황';$('#detailSub').innerHTML=`현재 조회 범위 <span class="scope-badge">상세 기준: <strong>${X(lowerVendor||'전체 업체')}</strong></span> · ${month()} · ${W(total)}억`}
function histMonths(){const ms=[...new Set(all().map(r=>r.d?.slice(0,7)).filter(Boolean))].sort(),cur=ms.at(-1);return{cur,hist:ms.filter(m=>m<cur)}}
function aggregate(m,v,mode){const mp={};scoped(v,m).forEach(r=>{const k=mode==='groups'?r.g:r.m;mp[k]=(mp[k]||0)+N(r.a)});return mp}
function sortAnalysis(arr,show){const idx=analysisSort;if(idx==='name')arr.sort((a,b)=>(analysisDir==='asc'?1:-1)*a.name.localeCompare(b.name,'ko'));else arr.sort((a,b)=>{const av=idx.startsWith('m:')?N(a.months[idx.slice(2)]):N(a[idx]),bv=idx.startsWith('m:')?N(b.months[idx.slice(2)]):N(b[idx]);return(analysisDir==='asc'?1:-1)*(av-bv)});return arr}
function renderAnalysis(){const t=$('#compareTable');if(!t)return;const mode=activeMode(),label=mode==='groups'?'제품군':'품목', {cur,hist}=histMonths();if(!cur||!hist.length){t.innerHTML='<tbody><tr><td>비교 가능한 확정월이 없습니다.</td></tr></tbody>';return}const current=aggregate(cur,lowerVendor,mode),full={};hist.forEach(m=>full[m]=aggregate(m,lowerVendor,mode));const keys=[...new Set([...Object.keys(current),...hist.flatMap(m=>Object.keys(full[m]))])],show=hist.slice(-6);let arr=keys.map(name=>{const avg=hist.reduce((s,m)=>s+N(full[m][name]),0)/hist.length,now=N(current[name]),prev=N(full[hist.at(-1)][name]);return{name,months:Object.fromEntries(show.map(m=>[m,N(full[m][name])])),avg,current:now,prev,diff:now-prev,ratio:avg?now/avg:0}});arr=sortAnalysis(arr,show).slice(0,180);$('#compareTitle').textContent=`${label}별 상세 분석`;const p=t.closest('section.panel')?.querySelector('.head p');if(p)p.innerHTML=`<span class="section-callout">현재 <strong>${X(lowerVendor||'전체 업체')}</strong> · <strong>${label} 기준</strong>으로 확정월 평균과 진행월 실적을 비교하고 있습니다. 표 제목을 클릭하면 오름/내림차순 정렬됩니다.</span>`;const th=(key,text)=>`<th class="analysis-sort ${analysisSort===key?'active':''}" data-sort="${X(key)}">${text} ${analysisSort===key?(analysisDir==='asc'?'▲':'▼'):'↕'}</th>`;t.innerHTML='<thead><tr>'+th('name',label)+show.map(m=>th('m:'+m,m.slice(2).replace('-','.'))).join('')+th('avg','확정월 평균')+th('current','진행월 현재')+th('prev','직전 확정월')+th('diff','직전월 대비 증감')+th('ratio','평균 대비율')+'</tr></thead><tbody>'+arr.map(r=>`<tr><td>${X(r.name)}</td>${show.map(m=>`<td>${W(r.months[m])}</td>`).join('')}<td>${W(r.avg)}</td><td>${W(r.current)}</td><td>${W(r.prev)}</td><td class="${r.diff>=0?'good':'bad'}">${r.diff>=0?'+':''}${W(r.diff)}</td><td class="${r.ratio>=1?'good':'bad'}">${P(r.ratio)}</td></tr>`).join('')+'</tbody>';$$('#compareTable th[data-sort]').forEach(h=>h.onclick=()=>{const k=h.dataset.sort;if(analysisSort===k)analysisDir=analysisDir==='asc'?'desc':'asc';else{analysisSort=k;analysisDir=k==='name'?'asc':'desc'}renderAnalysis()})}
function ensureTools(){const t=$('#detailTable'),sec=t?.closest('section.panel'),tabs=sec?.querySelector('.tabs');if(!t||!sec||!tabs)return;sec.querySelectorAll('.detail-tools,.scope-tools').forEach(x=>x.remove());const tools=document.createElement('div');tools.className='scope-tools';tools.innerHTML='<label>상세 업체 선택<select id="lowerVendor"></select></label><label>정렬 기준<select id="lowerSortKey"><option value="sales">매출액</option><option value="name">명칭</option></select></label><label>정렬 방향<select id="lowerSortDir"><option value="desc">내림차순</option><option value="asc">오름차순</option></select></label>';tabs.insertAdjacentElement('afterend',tools);const sel=$('#lowerVendor');sel.innerHTML='<option value="">전체 업체</option>'+KEY.map(v=>`<option value="${X(v)}">${X(v)}</option>`).join('')+'<option value="권역 외 업체">권역 외 업체</option>';sel.value=KEY.includes(lowerVendor)||lowerVendor==='권역 외 업체'?lowerVendor:'';sel.onchange=e=>{lowerVendor=e.target.value;renderLowerDetail();renderAnalysis()};$('#lowerSortKey').value=sortKey;$('#lowerSortDir').value=sortDir;$('#lowerSortKey').onchange=e=>{sortKey=e.target.value;renderLowerDetail()};$('#lowerSortDir').onchange=e=>{sortDir=e.target.value;renderLowerDetail()}}
function overrideTabs(){$$('.tabs .tab').forEach(b=>{b.onclick=e=>{e.preventDefault();e.stopPropagation();$$('.tabs .tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderLowerDetail();renderAnalysis()}})}
function update(){style();ensureOverviewRow();overrideUpperClicks();ensureTools();overrideTabs();renderLowerDetail();renderAnalysis();renderUpperGroup()}
function sig(){return[month(),$('#vendorTable')?.innerText?.length||0,window.SEED_DATA?.dailyRecords?.length||0,storedUploads().length].join('|')}
let tm;new MutationObserver(()=>{clearTimeout(tm);tm=setTimeout(()=>{const s=sig();if(s!==lastSig){lastSig=s;update()}else{ensureOverviewRow();overrideUpperClicks();overrideTabs()}},140)}).observe(document.body,{subtree:true,childList:true});setTimeout(()=>{lastSig=sig();update()},850);
})();