(()=>{'use strict';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const N=v=>Number(v||0),W=v=>(N(v)/1e8).toLocaleString('ko-KR',{minimumFractionDigits:1,maximumFractionDigits:1}),P=v=>Number.isFinite(v)?(v*100).toFixed(1)+'%':'-',X=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const KEY=['백제약품영등포지점','백제약품(주)영남본부','대전백제약품','백제약품(주)원주지점','(주)인천약품','(주)복산나이스','유진약품(주)','아이팜코리아(주)'];
let upperVendor='',lowerVendor='',sortKey='sales',sortDir='desc',lastSig='';
function style(){if($('#decoupleV20Style'))return;const s=document.createElement('style');s.id='decoupleV20Style';s.textContent=`
.scope-badge{display:inline-flex;align-items:center;gap:6px;margin-top:7px;padding:5px 9px;border-radius:999px;background:#0b2f45;border:1px solid #2c6886;color:#8bdcf2;font-size:11px;font-weight:800}.scope-badge strong{color:#fff}.overview-row td{background:linear-gradient(90deg,#123d5a,#0d2c43)!important;border-top:2px solid #4fd1c5!important;border-bottom:2px solid #4fd1c5!important}.overview-row{cursor:pointer!important}.overview-row:hover td{background:linear-gradient(90deg,#185273,#123c58)!important}.overview-cta{display:inline-flex;align-items:center;gap:6px;padding:6px 10px;border-radius:999px;background:#4fd1c5;color:#062033;font-weight:900;font-size:11px;box-shadow:0 0 0 2px rgba(79,209,197,.12)}.scope-tools{display:grid;grid-template-columns:1.4fr .9fr .8fr;gap:8px;margin:11px 0}.scope-tools label{font-size:11px;color:#91a9c1;font-weight:800}.scope-tools select{width:100%;margin-top:5px;padding:9px;border-radius:9px;border:1px solid #31506b;background:#071522;color:#eef6ff}.section-callout{margin:8px 0 12px;padding:10px 12px;border-left:3px solid #4fd1c5;border-radius:8px;background:#082033;color:#cfe6f6;font-size:12px}.section-callout strong{color:#fff}@media(max-width:720px){.scope-tools{grid-template-columns:1fr}}`;document.head.appendChild(s)}
function storedUploads(){try{const z=JSON.parse(localStorage.getItem('sales_forecast_v16')||localStorage.getItem('sales_forecast_v15')||'{}');return z.up||z.uploadRows||z.uploads||[]}catch(e){return[]}}
function seedRows(){const raw=window.SEED_DATA?.dailyRecords||[];return raw.map(r=>({d:r.date,v:r.vendor||'',g:r.productGroup||'미분류',m:r.material||'미분류',a:N(r.amount)}))}
function all(){const up=storedUploads(),rep=new Set(up.map(r=>r.d)),seed=seedRows().filter(r=>!rep.has(r.d));return seed.concat(up.map(r=>({d:r.d||r.date,v:r.v||r.vendor||'',g:r.g||r.productGroup||'미분류',m:r.m||r.material||'미분류',a:N(r.a??r.amount)})))}
const month=()=>$('#month')?.value||'';
function monthRows(m=month()){return all().filter(r=>r.d?.slice(0,7)===m)}
function vendorList(){return[...new Set(monthRows().map(r=>r.v).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'ko'))}
function scopeRows(v=lowerVendor,m=month()){let r=monthRows(m);return v?r.filter(x=>x.v===v):r}
function renderUpperGroup(){const t=$('#groupTable');if(!t)return;const rs=upperVendor?monthRows().filter(r=>r.v===upperVendor):monthRows(),mp={};rs.forEach(r=>mp[r.g]=(mp[r.g]||0)+N(r.a));const total=rs.reduce((s,r)=>s+N(r.a),0);t.innerHTML='<thead><tr><th>제품군</th><th>매출(억)</th><th>비중</th></tr></thead><tbody>'+Object.entries(mp).sort((a,b)=>b[1]-a[1]).map(([g,a])=>`<tr><td>${X(g)}</td><td>${W(a)}</td><td>${P(a/Math.max(1,total))}</td></tr>`).join('')+'</tbody>';const sec=t.closest('section.panel'),p=sec?.querySelector('.head p');if(p)p.innerHTML=`현재 조회 범위 <span class="scope-badge">제품군 기준: <strong>${X(upperVendor||'전체 업체')}</strong></span>`}
function makeOverviewClickable(){const body=$('#vendorTable tbody');if(!body)return;let row=[...body.rows].find(r=>(r.cells[0]?.innerText||'').trim()==='총합계');if(!row)return;row.classList.add('overview-row');row.tabIndex=0;row.setAttribute('role','button');row.setAttribute('aria-label','전체 현황 보기');row.cells[1].innerHTML='<span class="overview-cta">↺ 전체 현황 보기</span>';const go=()=>{upperVendor='';renderUpperGroup();$$('#vendorTable tr').forEach(r=>r.classList.remove('selected'));row.classList.add('selected')};row.onclick=go;row.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();go()}}}
function overrideUpperClicks(){const rows=$$('#vendorTable tr[data-v]');rows.forEach(r=>{const v=r.dataset.v;if(!v)return;r.onclick=e=>{e.preventDefault();e.stopPropagation();if(v==='백제약품 전체 합계'||v==='권역 외 업체'){upperVendor=v;const names=v==='백제약품 전체 합계'?KEY.slice(0,4):vendorList().filter(x=>!KEY.includes(x));const rs=monthRows().filter(x=>names.includes(x.v)),mp={};rs.forEach(x=>mp[x.g]=(mp[x.g]||0)+N(x.a));const t=$('#groupTable'),tot=rs.reduce((s,x)=>s+N(x.a),0);t.innerHTML='<thead><tr><th>제품군</th><th>매출(억)</th><th>비중</th></tr></thead><tbody>'+Object.entries(mp).sort((a,b)=>b[1]-a[1]).map(([g,a])=>`<tr><td>${X(g)}</td><td>${W(a)}</td><td>${P(a/Math.max(1,tot))}</td></tr>`).join('')+'</tbody>';const p=t.closest('section.panel')?.querySelector('.head p');if(p)p.innerHTML=`현재 조회 범위 <span class="scope-badge">제품군 기준: <strong>${X(v)}</strong></span>`}else{upperVendor=v;renderUpperGroup()}$$('#vendorTable tr').forEach(x=>x.classList.remove('selected'));r.classList.add('selected')};})}
function sortEntries(mp){let a=Object.entries(mp);a.sort((x,y)=>{if(sortKey==='name')return(sortDir==='asc'?1:-1)*x[0].localeCompare(y[0],'ko');return(sortDir==='asc'?1:-1)*(x[1]-y[1])});return a}
function renderLowerDetail(){const t=$('#detailTable');if(!t)return;const rs=scopeRows(),tab=$('.tabs .tab.active')?.dataset.tab||'materials',mp={};rs.forEach(r=>{const q=tab==='groups'?r.g:tab==='vendors'?r.v:r.m;mp[q]=(mp[q]||0)+N(r.a)});const total=rs.reduce((s,r)=>s+N(r.a),0);t.innerHTML='<thead><tr><th>'+(tab==='groups'?'제품군':tab==='vendors'?'업체':'품목(자재명)')+'</th><th>매출(억)</th><th>비중</th></tr></thead><tbody>'+sortEntries(mp).map(([q,a])=>`<tr><td>${X(q)}</td><td>${W(a)}</td><td>${P(a/Math.max(1,total))}</td></tr>`).join('')+'</tbody>';const title=$('#detailTitle');if(title)title.textContent='전체 상세 현황';const sub=$('#detailSub');if(sub)sub.innerHTML=`현재 조회 범위 <span class="scope-badge">상세 기준: <strong>${X(lowerVendor||'전체 업체')}</strong></span> · ${month()} · ${W(total)}억`}
function histMonths(){const ms=[...new Set(all().map(r=>r.d?.slice(0,7)).filter(Boolean))].sort(),cur=ms.at(-1);return{ms,cur,hist:ms.filter(m=>m<cur)}}
function fullByMaterial(m,v){const mp={};scopeRows(v,m).forEach(r=>mp[r.m]=(mp[r.m]||0)+N(r.a));return mp}
function renderProductAnalysis(){const t=$('#compareTable');if(!t)return;const{cur,hist}=histMonths();if(!cur||!hist.length){t.innerHTML='<tbody><tr><td>비교 가능한 확정월이 없습니다.</td></tr></tbody>';return}const cm=fullByMaterial(cur,lowerVendor),full={};hist.forEach(m=>full[m]=fullByMaterial(m,lowerVendor));const keys=[...new Set([...Object.keys(cm),...hist.flatMap(m=>Object.keys(full[m]))])],show=hist.slice(-6);const arr=keys.map(q=>{const avg=hist.reduce((s,m)=>s+N(full[m][q]),0)/hist.length,c=N(cm[q]),pv=N(full[hist.at(-1)][q]);return[q,avg,c,pv,c-pv,avg?c/avg:null]}).sort((a,b)=>b[2]-a[2]).slice(0,180);const title=$('#compareTitle');if(title)title.textContent='품목별 상세 분석';const sec=t.closest('section.panel'),p=sec?.querySelector('.head p');if(p)p.innerHTML=`<span class="section-callout">현재 <strong>${X(lowerVendor||'전체 업체')}</strong> 기준으로 품목별 확정월 평균과 진행월 실적을 비교하고 있습니다.</span>`;t.innerHTML='<thead><tr><th>품목</th>'+show.map(m=>`<th>${m.slice(2).replace('-','.')}</th>`).join('')+'<th>확정월 평균</th><th>진행월 현재</th><th>직전 확정월</th><th>직전월 대비 증감</th><th>평균 대비율</th></tr></thead><tbody>'+arr.map(r=>`<tr><td>${X(r[0])}</td>${show.map(m=>`<td>${W(full[m][r[0]]||0)}</td>`).join('')}<td>${W(r[1])}</td><td>${W(r[2])}</td><td>${W(r[3])}</td><td class="${r[4]>=0?'good':'bad'}">${r[4]>=0?'+':''}${W(r[4])}</td><td class="${r[5]!=null&&r[5]>=1?'good':'bad'}">${r[5]==null?'-':P(r[5])}</td></tr>`).join('')+'</tbody>'}
function ensureLowerTools(){const t=$('#detailTable'),sec=t?.closest('section.panel'),tabs=sec?.querySelector('.tabs');if(!t||!sec||!tabs)return;sec.querySelectorAll('.detail-tools').forEach(x=>x.remove());let tools=sec.querySelector('.scope-tools');if(!tools){tools=document.createElement('div');tools.className='scope-tools';tools.innerHTML='<label>상세 업체 선택<select id="lowerVendor"><option value="">전체 업체</option></select></label><label>정렬 기준<select id="lowerSortKey"><option value="sales">매출액</option><option value="name">명칭</option></select></label><label>정렬 방향<select id="lowerSortDir"><option value="desc">내림차순</option><option value="asc">오름차순</option></select></label>';tabs.insertAdjacentElement('afterend',tools);$('#lowerVendor').onchange=e=>{lowerVendor=e.target.value;renderLowerDetail();renderProductAnalysis()};$('#lowerSortKey').onchange=e=>{sortKey=e.target.value;renderLowerDetail()};$('#lowerSortDir').onchange=e=>{sortDir=e.target.value;renderLowerDetail()}}const sel=$('#lowerVendor'),opts=vendorList(),sig=opts.join('|');if(sel&&sel.dataset.sig!==sig){sel.innerHTML='<option value="">전체 업체</option>'+opts.map(v=>`<option value="${X(v)}">${X(v)}</option>`).join('');sel.dataset.sig=sig;if(opts.includes(lowerVendor))sel.value=lowerVendor}}
function overrideTabs(){$$('.tabs .tab').forEach(b=>{b.onclick=e=>{e.preventDefault();e.stopPropagation();$$('.tabs .tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderLowerDetail()}})}
function update(){style();makeOverviewClickable();overrideUpperClicks();ensureLowerTools();overrideTabs();renderLowerDetail();renderProductAnalysis();if(!upperVendor)renderUpperGroup()}
function signature(){return[month(),$('#vendorTable')?.innerText?.length||0,window.SEED_DATA?.dailyRecords?.length||0,storedUploads().length].join('|')}
let timer;const obs=new MutationObserver(()=>{clearTimeout(timer);timer=setTimeout(()=>{const s=signature();if(s!==lastSig){lastSig=s;update()}else{makeOverviewClickable();overrideUpperClicks();ensureLowerTools();overrideTabs()}},120)});obs.observe(document.body,{subtree:true,childList:true});setTimeout(()=>{lastSig=signature();update()},800);
})();