(()=>{'use strict';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],safe=s=>String(s||'export').replace(/[\\/:*?"<>|]/g,'_').replace(/\s+/g,'_'),month=()=>$('#month')?.value||'';
function style(){if($('#exportV21Style'))return;const s=document.createElement('style');s.id='exportV21Style';s.textContent=`.export-btn{appearance:none;border:1px solid #31506b;background:#0b2237;color:#cfe4f4;border-radius:8px;padding:6px 10px;font-size:11px;font-weight:700;cursor:pointer;white-space:nowrap}.export-btn:hover{border-color:#4fd1c5;color:#4fd1c5}.head{position:relative;padding-right:90px}.head>.export-btn{position:absolute;right:0;top:0}.top-actions{display:flex;gap:7px;align-items:center;flex-wrap:wrap;margin-top:8px}.panel{content-visibility:auto;contain-intrinsic-size:360px}.panel:first-of-type{content-visibility:visible}`;document.head.appendChild(s)}
function loadX(){if(window.XLSX)return Promise.resolve(window.XLSX);return new Promise((resolve,reject)=>{const urls=['https://cdn.jsdelivr.net/npm/xlsx@0.18.5/dist/xlsx.full.min.js','https://cdn.sheetjs.com/xlsx-0.20.3/package/dist/xlsx.full.min.js'];let i=0;const next=()=>{if(i>=urls.length)return reject(new Error('Excel 모듈 로딩 실패'));const s=document.createElement('script');s.src=urls[i++];s.async=true;s.onload=()=>resolve(window.XLSX);s.onerror=next;document.head.appendChild(s)};next()})}
function tableAOA(t){return t?[...t.rows].map(r=>[...r.cells].map(c=>c.innerText.trim())):[['데이터 없음']]}
function summaryAOA(){const a=[['구분','값','설명'],['기준월',month(),''],['월 MBO 목표(억)',$('#mbo')?.value||'',''],['1차 수금내역서 발행일',$('#first')?.value||'',''],['2차 수금내역서 발행일',$('#second')?.value||'','']];$$('#cards .card').forEach(c=>a.push([c.querySelector('.label')?.innerText.trim()||'',c.querySelector('.value')?.innerText.trim()||'',c.querySelector('.sub')?.innerText.trim()||'']));return a}
async function download(sheets,name,btn,label){try{if(btn){btn.disabled=true;btn.textContent='생성중…'}const X=await loadX(),wb=X.utils.book_new();for(const[s,a]of sheets)X.utils.book_append_sheet(wb,X.utils.aoa_to_sheet(a),String(s).slice(0,31));X.writeFile(wb,`${safe(name)}_${month()||'전체'}.xlsx`)}finally{if(btn){btn.disabled=false;btn.textContent=label||'Excel'}}}
const sections=[['groupTargetTable','제품군_MBO_업체별_필요매출'],['vendorTable','권역_업체현황'],['groupTable','제품군현황'],['dailyTable','일자별_기준누계'],['detailTable','전체_상세현황'],['compareTable','품목별_상세분석']];
function install(){style();$$('.card-export').forEach(x=>x.remove());const top=$('.top>div:first-child');if(top&&!$('#summaryExportBtn')){let box=top.querySelector('.top-actions');if(!box){box=document.createElement('div');box.className='top-actions';top.appendChild(box)}const b=document.createElement('button');b.id='summaryExportBtn';b.className='export-btn';b.textContent='요약 Excel';b.onclick=()=>download([['요약',summaryAOA()]],'Sales_Forecast_요약',b,'요약 Excel');box.appendChild(b)}sections.forEach(([id,name])=>{const t=document.getElementById(id),h=t?.closest('section.panel')?.querySelector('.head');if(h&&!h.querySelector('.export-btn')){const b=document.createElement('button');b.className='export-btn';b.textContent='Excel';b.onclick=()=>download([[name,tableAOA(t)]],name,b,'Excel');h.appendChild(b)}})}
let tm;new MutationObserver(()=>{clearTimeout(tm);tm=setTimeout(install,120)}).observe(document.body,{subtree:true,childList:true});install();
})();