(()=>{'use strict';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const safe=s=>String(s||'export').replace(/[\\/:*?"<>|]/g,'_').replace(/\s+/g,'_');
const month=()=>$('#month')?.value||'';
const status=m=>{const e=$('#status'); if(e)e.textContent=m};
function style(){if($('#exportV17Style'))return;const s=document.createElement('style');s.id='exportV17Style';s.textContent=`
.export-btn{appearance:none;border:1px solid #31506b;background:#0b2237;color:#cfe4f4;border-radius:8px;padding:6px 9px;font-size:11px;font-weight:700;cursor:pointer;white-space:nowrap}.export-btn:hover{border-color:#4fd1c5;color:#4fd1c5}.export-btn:disabled{opacity:.55;cursor:wait}.head{position:relative;padding-right:90px}.head>.export-btn{position:absolute;right:0;top:0}.card{position:relative}.card>.card-export{position:absolute;right:10px;top:10px;padding:3px 6px;font-size:10px;opacity:.72}.card:hover>.card-export{opacity:1}.top-actions{display:flex;gap:7px;align-items:center;flex-wrap:wrap;margin-top:8px}.panel{content-visibility:auto;contain-intrinsic-size:360px}.panel:first-of-type{content-visibility:visible}`;document.head.appendChild(s)}
function loadX(){if(window.XLSX)return Promise.resolve(window.XLSX);return new Promise((resolve,reject)=>{const urls=['https://cdn.jsdelivr.net/npm/xlsx@0.18.5/dist/xlsx.full.min.js','https://cdn.sheetjs.com/xlsx-0.20.3/package/dist/xlsx.full.min.js'];let i=0;const next=()=>{if(i>=urls.length)return reject(new Error('Excel 모듈 로딩 실패'));const s=document.createElement('script');s.src=urls[i++];s.async=true;s.onload=()=>resolve(window.XLSX);s.onerror=next;document.head.appendChild(s)};next()})}
function tableAOA(table){if(!table)return [['데이터 없음']];return [...table.rows].map(tr=>[...tr.cells].map(td=>td.innerText.trim()))}
function cardAOA(card){const label=card.querySelector('.label')?.innerText.trim()||'지표';const value=card.querySelector('.value')?.innerText.trim()||'';const sub=card.querySelector('.sub')?.innerText.trim()||'';return [['기준월',month()],['지표',label],['값',value],['설명',sub]]}
async function download(sheets,name,btn){try{if(btn){btn.disabled=true;btn.textContent='생성중…'}const XLSX=await loadX();const wb=XLSX.utils.book_new();for(const [sheet,aoa] of sheets){const ws=XLSX.utils.aoa_to_sheet(aoa);XLSX.utils.book_append_sheet(wb,ws,String(sheet).slice(0,31))}XLSX.writeFile(wb,`${safe(name)}_${month()||'전체'}.xlsx`);status('Excel 추출 완료 · '+name)}catch(e){status('Excel 추출 오류: '+e.message)}finally{if(btn){btn.disabled=false;btn.textContent='Excel'}}}
function addCardButtons(){const cards=$$('#cards .card');cards.forEach((card,i)=>{if(card.querySelector('.card-export'))return;const b=document.createElement('button');b.type='button';b.className='export-btn card-export';b.textContent='Excel';b.title='이 카드만 Excel로 추출';b.onclick=e=>{e.stopPropagation();const label=card.querySelector('.label')?.innerText.trim()||`KPI_${i+1}`;download([[label,cardAOA(card)]],label,b)};card.appendChild(b)})}
const sections=[['groupTargetTable','제품군_MBO_업체별_필요매출'],['vendorTable','권역_업체현황'],['groupTable','제품군현황'],['dailyTable','일자별_기준누계'],['detailTable','전체_상세현황'],['compareTable','확정월평균_진행월비교']];
function addSectionButtons(){sections.forEach(([id,name])=>{const t=document.getElementById(id);if(!t)return;const sec=t.closest('section.panel');const head=sec?.querySelector('.head');if(!head||head.querySelector('.export-btn'))return;const b=document.createElement('button');b.type='button';b.className='export-btn';b.textContent='Excel';b.onclick=()=>download([[name,tableAOA(t)]],name,b);head.appendChild(b)})}
function addTopButton(){const top=$('.top>div:first-child');if(!top||$('#exportAllBtn'))return;const box=document.createElement('div');box.className='top-actions';const b=document.createElement('button');b.id='exportAllBtn';b.type='button';b.className='export-btn';b.textContent='전체 Excel 추출';b.onclick=()=>{const sheets=[];$$('#cards .card').forEach((c,i)=>{const label=c.querySelector('.label')?.innerText.trim()||`KPI${i+1}`;sheets.push([`KPI_${i+1}`,cardAOA(c)])});sections.forEach(([id,name])=>{const t=document.getElementById(id);if(t)sheets.push([name,tableAOA(t)])});download(sheets,'Sales_Forecast_전체',b)};box.appendChild(b);top.appendChild(box)}
function install(){style();addTopButton();addCardButtons();addSectionButtons()}
let timer=null;const obs=new MutationObserver(()=>{clearTimeout(timer);timer=setTimeout(install,80)});obs.observe(document.body,{subtree:true,childList:true});install();
if('serviceWorker'in navigator){window.addEventListener('load',()=>navigator.serviceWorker.register('./sw-v17.js',{scope:'./'}).catch(()=>{}),{once:true})}
})();