(()=>{'use strict';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const safe=s=>String(s||'export').replace(/[\\/:*?"<>|]/g,'_').replace(/\s+/g,'_');
const month=()=>$('#month')?.value||'';
const status=m=>{const e=$('#status');if(e)e.textContent=m};
const parseWon=t=>{const m=String(t||'').replace(/,/g,'').match(/-?\d+(?:\.\d+)?/);return m?Number(m[0]):0};
function style(){if($('#exportV18Style'))return;const s=document.createElement('style');s.id='exportV18Style';s.textContent=`
.export-btn{appearance:none;border:1px solid #31506b;background:#0b2237;color:#cfe4f4;border-radius:8px;padding:6px 10px;font-size:11px;font-weight:700;cursor:pointer;white-space:nowrap}.export-btn:hover{border-color:#4fd1c5;color:#4fd1c5}.export-btn:disabled{opacity:.55;cursor:wait}.head{position:relative;padding-right:90px}.head>.export-btn{position:absolute;right:0;top:0}.top-actions{display:flex;gap:7px;align-items:center;flex-wrap:wrap;margin-top:8px}.detail-tools{display:grid;grid-template-columns:1.4fr .9fr .8fr;gap:8px;margin:10px 0 6px}.detail-tools label{font-size:11px;color:#91a9c1;font-weight:700}.detail-tools select{width:100%;margin-top:5px;padding:8px;border-radius:8px;border:1px solid #29445f;background:#071522;color:#eef6ff}.panel{content-visibility:auto;contain-intrinsic-size:360px}.panel:first-of-type{content-visibility:visible}.total-row td{font-weight:850;background:#0a2942;border-top:1px solid #4a6f90}.region-total td{font-weight:800;background:#0b2237;border-top:1px solid #34516f}@media(max-width:720px){.detail-tools{grid-template-columns:1fr}}`;
document.head.appendChild(s)}
function loadX(){if(window.XLSX)return Promise.resolve(window.XLSX);return new Promise((resolve,reject)=>{const urls=['https://cdn.jsdelivr.net/npm/xlsx@0.18.5/dist/xlsx.full.min.js','https://cdn.sheetjs.com/xlsx-0.20.3/package/dist/xlsx.full.min.js'];let i=0;const next=()=>{if(i>=urls.length)return reject(new Error('Excel 모듈 로딩 실패'));const sc=document.createElement('script');sc.src=urls[i++];sc.async=true;sc.onload=()=>resolve(window.XLSX);sc.onerror=next;document.head.appendChild(sc)};next()})}
function tableAOA(table){if(!table)return[['데이터 없음']];return[...table.rows].map(tr=>[...tr.cells].map(td=>td.innerText.trim()))}
async function download(sheets,name,btn,label='Excel'){try{if(btn){btn.disabled=true;btn.textContent='생성중…'}const XLSX=await loadX(),wb=XLSX.utils.book_new();for(const[sheet,aoa]of sheets){const ws=XLSX.utils.aoa_to_sheet(aoa);XLSX.utils.book_append_sheet(wb,ws,String(sheet).slice(0,31))}XLSX.writeFile(wb,`${safe(name)}_${month()||'전체'}.xlsx`);status('Excel 추출 완료 · '+name)}catch(e){status('Excel 추출 오류: '+e.message)}finally{if(btn){btn.disabled=false;btn.textContent=label}}}
function summaryAOA(){const a=[['구분','값','설명'],['기준월',month(),''],['월 MBO 목표(억)',$('#mbo')?.value||'','월별 직접 입력'],['1차 수금내역서 발행일',$('#first')?.value||'',''],['2차 수금내역서 발행일',$('#second')?.value||'','']];$$('#cards .card').forEach(c=>a.push([c.querySelector('.label')?.innerText.trim()||'',c.querySelector('.value')?.innerText.trim()||'',c.querySelector('.sub')?.innerText.trim()||'']));return a}
const sections=[['groupTargetTable','제품군_MBO_업체별_필요매출'],['vendorTable','권역_업체현황'],['groupTable','제품군현황'],['dailyTable','일자별_기준누계'],['detailTable','업체_상세현황'],['compareTable','확정월평균_진행월비교']];
function removeCardButtons(){$$('.card-export').forEach(x=>x.remove())}
function addSummaryButton(){const top=$('.top>div:first-child');if(!top)return;let box=top.querySelector('.top-actions');if(!box){box=document.createElement('div');box.className='top-actions';top.appendChild(box)}let b=$('#summaryExportBtn');if(!b){b=document.createElement('button');b.id='summaryExportBtn';b.type='button';b.className='export-btn';b.textContent='요약 Excel';b.onclick=()=>download([['요약',summaryAOA()]],'Sales_Forecast_요약',b,'요약 Excel');box.appendChild(b)}const old=$('#exportAllBtn');if(old)old.remove()}
function addSectionButtons(){sections.forEach(([id,name])=>{const t=document.getElementById(id),sec=t?.closest('section.panel'),head=sec?.querySelector('.head');if(!head)return;let b=head.querySelector('.export-btn');if(!b){b=document.createElement('button');b.type='button';b.className='export-btn';b.textContent='Excel';b.onclick=()=>download([[name,tableAOA(t)]],name,b);head.appendChild(b)}})}
function augmentVendorTotals(){const t=$('#vendorTable'),body=t?.tBodies?.[0];if(!body)return;body.querySelectorAll('.v18-added').forEach(x=>x.remove());const other=[...body.rows].find(r=>(r.cells[0]?.innerText||'').trim()==='권역 외 업체');if(!other)return;const totalCard=$$('#cards .card').find(c=>(c.querySelector('.label')?.innerText||'').trim()==='현재 누계');const grand=parseWon(totalCard?.querySelector('.value')?.innerText),outside=parseWon(other.cells[2]?.innerText),regional=Math.max(0,grand-outside);const share=x=>grand?`${(x/grand*100).toFixed(1)}%`:'-';const r=document.createElement('tr');r.className='v18-added region-total';r.innerHTML=`<td>권역 합계</td><td>지정 8개 업체 합계</td><td>${regional.toFixed(1)}</td><td>${share(regional)}</td>`;body.insertBefore(r,other);const g=document.createElement('tr');g.className='v18-added total-row';g.innerHTML=`<td>총합계</td><td>권역 합계 + 권역 외</td><td>${grand.toFixed(1)}</td><td>100.0%</td>`;body.appendChild(g)}
function vendorOptions(){const t=$('#vendorTable');if(!t)return[];return[...new Set([...t.querySelectorAll('tr[data-v]')].map(r=>r.dataset.v).filter(v=>v&&v!=='백제약품 전체 합계'&&v!=='권역 외 업체'))].sort((a,b)=>a.localeCompare(b,'ko'))}
function ensureDetailTools(){const table=$('#detailTable'),sec=table?.closest('section.panel'),tabs=sec?.querySelector('.tabs');if(!table||!sec||!tabs)return;let tools=sec.querySelector('.detail-tools');if(!tools){tools=document.createElement('div');tools.className='detail-tools';tools.innerHTML=`<label>업체 선택<select id="detailVendorFilter"><option value="">전체 업체</option></select></label><label>정렬 기준<select id="detailSortKey"><option value="sales">매출액</option><option value="name">명칭</option><option value="share">비중</option></select></label><label>정렬 방향<select id="detailSortDir"><option value="desc">내림차순</option><option value="asc">오름차순</option></select></label>`;tabs.insertAdjacentElement('afterend',tools);$('#detailVendorFilter').onchange=e=>{const v=e.target.value;if(!v){const m=$('#month');m?.dispatchEvent(new Event('change',{bubbles:true}));return}const row=[...document.querySelectorAll('#vendorTable tr[data-v]')].find(r=>r.dataset.v===v);if(row)row.click()};$('#detailSortKey').onchange=sortDetail;$('#detailSortDir').onchange=sortDetail}
const sel=$('#detailVendorFilter'),keep=sel?.value||'';if(sel){const opts=vendorOptions();sel.innerHTML='<option value="">전체 업체</option>'+opts.map(v=>`<option value="${v.replace(/"/g,'&quot;')}">${v}</option>`).join('');const title=$('#detailTitle')?.innerText||'';const active=opts.find(v=>title.includes(v));sel.value=active|| (opts.includes(keep)?keep:'')}}}
function sortDetail(){const t=$('#detailTable'),body=t?.tBodies?.[0];if(!body)return;const key=$('#detailSortKey')?.value||'sales',dir=$('#detailSortDir')?.value||'desc',rows=[...body.rows];rows.sort((a,b)=>{let av,bv;if(key==='name'){av=(a.cells[0]?.innerText||'');bv=(b.cells[0]?.innerText||'');return(dir==='asc'?1:-1)*av.localeCompare(bv,'ko')}const idx=key==='share'?2:1;av=parseWon(a.cells[idx]?.innerText);bv=parseWon(b.cells[idx]?.innerText);return(dir==='asc'?1:-1)*(av-bv)});rows.forEach(r=>body.appendChild(r))}
function install(){style();removeCardButtons();addSummaryButton();addSectionButtons();augmentVendorTotals();ensureDetailTools();sortDetail()}
let timer;const obs=new MutationObserver(()=>{clearTimeout(timer);timer=setTimeout(install,80)});obs.observe(document.body,{subtree:true,childList:true});install();
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw-v18.js',{scope:'./'}).catch(()=>{}),{once:true});
})();