(()=>{'use strict';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],safe=s=>String(s||'export').replace(/[\\/:*?"<>|]/g,'_').replace(/\s+/g,'_'),month=()=>$('#month')?.value||'';
const KEY=['백제약품영등포지점','백제약품(주)영남본부','대전백제약품','백제약품(주)원주지점','(주)인천약품','(주)복산나이스','유진약품(주)','아이팜코리아(주)'],BK=KEY.slice(0,4),STORE='sales_forecast_v16';
function style(){if($('#exportV21Style'))return;const s=document.createElement('style');s.id='exportV21Style';s.textContent=`.export-btn{appearance:none;border:1px solid #31506b;background:#0b2237;color:#cfe4f4;border-radius:8px;padding:6px 10px;font-size:11px;font-weight:700;cursor:pointer;white-space:nowrap}.export-btn:hover{border-color:#4fd1c5;color:#4fd1c5}.head{position:relative;padding-right:90px}.head>.export-btn{position:absolute;right:0;top:0}.top-actions{display:flex;gap:7px;align-items:center;flex-wrap:wrap;margin-top:8px}.panel{content-visibility:auto;contain-intrinsic-size:360px}.panel:first-of-type{content-visibility:visible}`;document.head.appendChild(s)}
function loadX(){if(window.XLSX)return Promise.resolve(window.XLSX);return new Promise((resolve,reject)=>{const urls=['https://cdn.jsdelivr.net/npm/xlsx@0.18.5/dist/xlsx.full.min.js','https://cdn.sheetjs.com/xlsx-0.20.3/package/dist/xlsx.full.min.js'];let i=0;const next=()=>{if(i>=urls.length)return reject(new Error('Excel 모듈 로딩 실패'));const s=document.createElement('script');s.src=urls[i++];s.async=true;s.onload=()=>resolve(window.XLSX);s.onerror=next;document.head.appendChild(s)};next()})}
function excelValue(txt){const s=String(txt??'').trim();if(!s)return'';if(/^[-+]?\d[\d,]*(?:\.\d+)?%$/.test(s))return Number(s.replace(/[,%]/g,''));if(/^[-+]?\d[\d,]*(?:\.\d+)?(?:억)?$/.test(s))return Number(s.replace(/[,억]/g,''));if(/^[-+]?\d[\d,]*(?:\.\d+)?\s*✓$/.test(s))return Number(s.replace(/[,✓\s]/g,''));return s}
function tableAOA(t){return t?[...t.rows].map(r=>[...r.cells].map(c=>excelValue(c.innerText))):[['데이터 없음']]}
function autoWidth(ws,a){const n=Math.max(0,...a.map(r=>r.length));ws['!cols']=Array.from({length:n},(_,i)=>({wch:Math.min(36,Math.max(10,...a.map(r=>String(r[i]??'').length+2)))}))}
async function download(sheets,name,btn,label){try{if(btn){btn.disabled=true;btn.textContent='생성중…'}const X=await loadX(),wb=X.utils.book_new();for(const[s,a]of sheets){const ws=X.utils.aoa_to_sheet(a);autoWidth(ws,a);X.utils.book_append_sheet(wb,ws,String(s).slice(0,31))}X.writeFile(wb,`${safe(name)}_${month()||'전체'}.xlsx`)}finally{if(btn){btn.disabled=false;btn.textContent=label||'Excel'}}}
function state(){try{return JSON.parse(localStorage.getItem(STORE)||localStorage.getItem('sales_forecast_v15')||'{}')}catch(e){return{}}}
function stored(){const z=state();const a=z.up||z.uploadRows||z.uploads;if(Array.isArray(a)&&a.length)return a;return window.__SF_SHARED_UPLOADS||[]}
function seed(){return(window.SEED_DATA?.dailyRecords||[]).map(r=>({d:r.date,v:r.vendor||'',g:r.productGroup||'미분류',a:Number(r.amount||0)}))}
function allRows(){const up=stored().map(r=>({d:r.d||r.date,v:r.v||r.vendor||'',g:r.g||r.productGroup||'미분류',a:Number(r.a??r.amount??0)})),rep=new Set(up.map(r=>r.d));return seed().filter(r=>!rep.has(r.d)).concat(up)}
function groupRows(m,g){return allRows().filter(r=>r.d?.slice(0,7)===m&&r.g===g)}
function vendorMap(rs){const mp={};rs.forEach(r=>mp[r.v]=(mp[r.v]||0)+Number(r.a||0));return mp}
function productGap(g,targetEok){const cur=month(),hist=[...new Set(allRows().map(r=>r.d?.slice(0,7)).filter(m=>m&&m<cur))].sort(),avg={};KEY.forEach(v=>avg[v]=0);hist.forEach(m=>{const mp=vendorMap(groupRows(m,g));KEY.forEach(v=>avg[v]+=Number(mp[v]||0))});KEY.forEach(v=>avg[v]=hist.length?avg[v]/hist.length:0);const managedAvg=KEY.reduce((s,v)=>s+avg[v],0),shares={};KEY.forEach(v=>shares[v]=managedAvg?avg[v]/managedAvg:1/KEY.length);const cm=vendorMap(groupRows(cur,g)),outsideNow=Object.keys(cm).filter(v=>!KEY.includes(v)).reduce((s,v)=>s+Number(cm[v]||0),0),curTotal=KEY.reduce((s,v)=>s+Number(cm[v]||0),0)+outsideNow,target=Number(targetEok||0)*1e8,totalNeed=Math.max(0,target-curTotal),gap={},rows=[];let remain=totalNeed;KEY.forEach((v,i)=>{const add=i===KEY.length-1?remain:Math.round(totalNeed*shares[v]);if(i!==KEY.length-1)remain-=add;gap[v]=add;rows.push(add)});gap['권역 외 업체']=0;gap['백제약품 전체 합계']=BK.reduce((s,v)=>s+Number(gap[v]||0),0);gap['총합계']=rows.reduce((s,v)=>s+v,0);return gap}
function vendorNameFromRow(r){const c0=String(r.cells?.[0]?.innerText||'').trim(),c1=String(r.cells?.[1]?.innerText||'').trim();if(c0==='백제약품 전체 합계')return'백제약품 전체 합계';if(c0==='권역 외 업체')return'권역 외 업체';if(c0==='총합계')return'총합계';return c1}
function vendorAOA(t){const base=tableAOA(t),z=state(),gmbo=(z.gmbo||z.groupMbo||{})[month()]||{},groups=Object.entries(gmbo).filter(([,v])=>v!==''&&v!=null&&Number.isFinite(Number(v))&&Number(v)>=0);if(!groups.length)return base;const gaps=Object.fromEntries(groups.map(([g,v])=>[g,productGap(g,Number(v))]));const out=[...base.map(r=>[...r])];groups.forEach(([g])=>out[0].push(`${g} 추가 필요액`));[...t.tBodies].flatMap(b=>[...b.rows]).forEach((r,i)=>{const name=vendorNameFromRow(r),row=out[i+1];if(!row)return;groups.forEach(([g])=>row.push(Number(gaps[g]?.[name]||0)/1e8))});return out}
function cloneWithValues(node){const c=node.cloneNode(true),src=node.querySelectorAll('input,select,textarea'),dst=c.querySelectorAll('input,select,textarea');src.forEach((el,i)=>{const d=dst[i];if(!d)return;if(el.tagName==='SELECT'){[...d.options].forEach(o=>o.selected=false);if(d.options[el.selectedIndex])d.options[el.selectedIndex].selected=true}else if(el.type==='checkbox'||el.type==='radio'){if(el.checked)d.setAttribute('checked','checked');else d.removeAttribute('checked')}else d.setAttribute('value',el.value||'')});return c}
function printSummary(){const top=document.querySelector('.top'),control=document.querySelector('section.panel .controls')?.closest('section.panel'),cards=document.querySelector('#cards'),help=document.querySelector('.help')?.closest('section.panel');if(!top||!control||!cards){alert('인쇄할 요약 영역을 찾지 못했습니다.');return}const wrap=document.createElement('div');[top,control,cards,help].filter(Boolean).forEach(n=>wrap.appendChild(cloneWithValues(n)));wrap.querySelectorAll('.top-actions,.export-btn,.upload input[type=file]').forEach(n=>n.remove());const css=`@page{size:A4 landscape;margin:10mm}*{box-sizing:border-box}body{margin:0;font-family:Arial,'Noto Sans KR',sans-serif;color:#111;background:#fff}.print-wrap{width:100%}.top{display:flex;justify-content:space-between;align-items:flex-start;margin-bottom:12px}.eyebrow{font-size:11px;font-weight:800;letter-spacing:.12em;color:#246b7a}h1{margin:4px 0 4px;font-size:24px}.muted,.status{color:#555;font-size:11px}.panel,.card{border:1px solid #cfd8df;border-radius:10px;background:#fff}.panel{padding:12px;margin-bottom:10px}.controls{display:grid;grid-template-columns:repeat(5,1fr);gap:8px}.controls label{font-size:10px;font-weight:700;color:#444}.controls input,.controls select{width:100%;margin-top:4px;padding:7px;border:1px solid #bbb;border-radius:6px;background:#fff;color:#111}.upload{display:none!important}.cards{display:grid;grid-template-columns:repeat(4,1fr);gap:8px;margin-bottom:10px}.card{padding:12px;min-height:86px}.label{font-size:10px;color:#666}.value{font-size:22px;font-weight:800;margin-top:6px}.sub{font-size:9px;color:#666;margin-top:4px}.good,.warn,.bad,.info{color:#111}.help{display:grid;grid-template-columns:repeat(4,1fr);gap:8px}.help div{border:1px solid #d9e1e7;border-radius:8px;padding:9px}.help b{display:block;font-size:10px;margin-bottom:4px}.help span{font-size:9px;line-height:1.35;color:#444}.pill{border:1px solid #bbb;border-radius:999px;padding:4px 8px;font-size:10px}.print-title{font-size:10px;color:#666;margin:0 0 8px}@media print{button{display:none!important}}`;const w=window.open('','_blank','width=1280,height=900');if(!w){alert('팝업이 차단되어 인쇄창을 열 수 없습니다. 브라우저에서 팝업을 허용해 주세요.');return}w.document.open();w.document.write(`<!doctype html><html lang="ko"><head><meta charset="utf-8"><title>Sales Forecast 요약 인쇄</title><style>${css}</style></head><body><div class="print-wrap"><div class="print-title">SCM SALES Forecast CONTROL TOWER · ${month()}</div>${wrap.innerHTML}</div><script>window.onload=()=>{setTimeout(()=>window.print(),150)};<\/script></body></html>`);w.document.close()}
const sections=[['groupTargetTable','제품군_MBO_업체별_필요매출'],['vendorTable','권역_업체현황'],['groupTable','제품군현황'],['dailyTable','일자별_기준누계'],['detailTable','전체_상세현황'],['compareTable','품목별_상세분석']];
function install(){style();$$('.card-export').forEach(x=>x.remove());const top=$('.top>div:first-child');if(top){let box=top.querySelector('.top-actions');if(!box){box=document.createElement('div');box.className='top-actions';top.appendChild(box)}let b=$('#summaryExportBtn');if(!b){b=document.createElement('button');b.id='summaryExportBtn';b.className='export-btn';box.appendChild(b)}b.textContent='요약 인쇄';b.onclick=printSummary}sections.forEach(([id,name])=>{const t=document.getElementById(id),h=t?.closest('section.panel')?.querySelector('.head');if(h&&!h.querySelector('.export-btn')){const b=document.createElement('button');b.className='export-btn';b.textContent='Excel';b.onclick=()=>{const a=id==='vendorTable'?vendorAOA(t):tableAOA(t);download([[name,a]],name,b,'Excel')};h.appendChild(b)}})}
let tm;new MutationObserver(()=>{clearTimeout(tm);tm=setTimeout(install,120)}).observe(document.body,{subtree:true,childList:true});install();
})();