(()=>{'use strict';
const $=s=>document.querySelector(s),N=v=>Number(v||0),W=v=>(N(v)/1e8).toLocaleString('ko-KR',{minimumFractionDigits:1,maximumFractionDigits:1}),P=v=>Number.isFinite(v)?(v*100).toFixed(1)+'%':'-',X=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function setTitle(){const eyebrow=$('.eyebrow'),h1=$('.top h1');if(eyebrow)eyebrow.textContent='SCM SALES Forecast CONTROL TOWER';if(h1)h1.textContent='종합도매 매출 · MBO 운영 대시보드';document.title='SCM SALES Forecast CONTROL TOWER | 종합도매 매출 · MBO 운영 대시보드'}
function reorderDetailTabs(){const tabs=$('.tabs');if(!tabs)return;const vendor=tabs.querySelector('[data-tab="vendors"]'),group=tabs.querySelector('[data-tab="groups"]'),material=tabs.querySelector('[data-tab="materials"]');if(vendor){vendor.textContent='업체';tabs.appendChild(vendor)}if(group){group.textContent='품목군';tabs.appendChild(group)}if(material){material.textContent='품목(상세)';tabs.appendChild(material)}}
function storedUploads(){try{const z=JSON.parse(localStorage.getItem('sales_forecast_v16')||localStorage.getItem('sales_forecast_v15')||'{}');return z.up||z.uploadRows||z.uploads||[]}catch(e){return[]}}
function rows(){const raw=window.SEED_DATA?.dailyRecords||[],up=storedUploads(),rep=new Set(up.map(r=>r.d||r.date)),seed=raw.map(r=>({d:r.date,v:r.vendor||'',g:r.productGroup||'미분류',a:N(r.amount)})).filter(r=>!rep.has(r.d));return seed.concat(up.map(r=>({d:r.d||r.date,v:r.v||r.vendor||'',g:r.g||r.productGroup||'미분류',a:N(r.a??r.amount)})))}
function renderAllGroups(){const month=$('#month')?.value||'',rs=rows().filter(r=>r.d?.slice(0,7)===month),mp={};rs.forEach(r=>mp[r.g]=(mp[r.g]||0)+N(r.a));const total=rs.reduce((s,r)=>s+N(r.a),0),t=$('#groupTable');if(!t)return;t.innerHTML='<thead><tr><th>제품군</th><th>매출(억)</th><th>비중</th></tr></thead><tbody>'+Object.entries(mp).sort((a,b)=>b[1]-a[1]).map(([g,a])=>`<tr><td>${X(g)}</td><td>${W(a)}</td><td>${P(a/Math.max(1,total))}</td></tr>`).join('')+'</tbody>';const sec=t.closest('section.panel'),h=sec?.querySelector('.head h3'),p=sec?.querySelector('.head p');if(h)h.innerHTML='제품군 현황 <span class="scope-badge">현재 기준: <strong>전체 업체</strong></span>';if(p)p.textContent='전체 업체의 제품군 매출 현황입니다.';document.querySelectorAll('#vendorTable tr').forEach(r=>r.classList.remove('selected'));const row=$('#vendorTable .overview-row');if(row)row.classList.add('selected');const st=$('#status');if(st)st.textContent='전체 업체 기준 제품군 현황으로 전환했습니다.'}
function isOverviewTarget(target){return !!target.closest?.('#vendorTable .overview-row, #vendorTable .overview-cta')}
function clickHandler(e){if(!isOverviewTarget(e.target))return;e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();renderAllGroups()}
function keyHandler(e){if((e.key!=='Enter'&&e.key!==' ')||!isOverviewTarget(e.target))return;e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();renderAllGroups()}
document.addEventListener('click',clickHandler,true);document.addEventListener('keydown',keyHandler,true);setTitle();reorderDetailTabs();setTimeout(()=>{setTitle();reorderDetailTabs()},500);
})();