(()=>{'use strict';
const REPO='yhbae106/Sales_Forecast',BRANCH='main',API='https://api.github.com/repos/yhbae106/Sales_Forecast/contents/shared-data/sales-history.json',STORE='sales_forecast_v16',CLOSE_KEY='sales_forecast_vendor_closed_v66',AUTH_KEY='sales_forecast_master_auth_v77';
const $=s=>document.querySelector(s),status=m=>{const e=$('#status');if(e)e.textContent=m};window.__sfMasterToken=null;
const enc=new TextEncoder(),dec=new TextDecoder(),b64=a=>btoa(String.fromCharCode(...new Uint8Array(a))),unb64=s=>Uint8Array.from(atob(s),c=>c.charCodeAt(0));
function lastDateOf(s){const a=(s?.sourceFiles||[]).map(x=>x.lastDate||x.date).filter(Boolean),b=(s?.uploads||[]).map(x=>x.d||x.date).filter(Boolean);return[...a,...b].sort().at(-1)||''}
function lastSharedDate(){const d=lastDateOf(window.__sfSharedMeta||{});return d?`${Number(d.slice(5,7))}/${Number(d.slice(8))}까지 반영 완료`:'공용 매출 데이터 연결 완료 · 마스터 업로드 대기'}
function addStyle(){if($('#sharedV31Style'))return;const s=document.createElement('style');s.id='sharedV31Style';s.textContent=`.master-bar{display:flex;gap:8px;align-items:center;flex-wrap:wrap;margin-top:10px}.master-btn{border:1px solid #31506b;background:#0b2237;color:#cfe4f4;border-radius:8px;padding:7px 10px;font-size:11px;font-weight:800;cursor:pointer}.master-btn.on{border-color:#4fd1c5;color:#4fd1c5;background:#0a2c32}.master-badge{font-size:11px;color:#91a9c1}.master-badge.on{color:#59d98e}.upload.locked{opacity:.62}.master-locked{opacity:.62;cursor:not-allowed}.master-only-note{display:block;margin-top:4px;font-size:9px;color:#ffb454}.sf-auth-modal{position:fixed;inset:0;z-index:100000;background:rgba(3,10,18,.72);display:flex;align-items:center;justify-content:center}.sf-auth-box{width:min(440px,calc(100vw - 28px));background:#0f2135;border:1px solid #31506b;border-radius:16px;padding:20px;box-shadow:0 18px 60px rgba(0,0,0,.45)}.sf-auth-box h3{margin:0 0 6px;font-size:17px}.sf-auth-box p{margin:0 0 14px;color:#91a9c1;font-size:11px;line-height:1.5}.sf-auth-box label{display:block;margin:10px 0;color:#b9cada;font-size:11px;font-weight:800}.sf-auth-box input{width:100%;margin-top:5px;padding:10px;border-radius:9px;border:1px solid #31506b;background:#071522;color:#eef6ff;font-size:14px}.sf-auth-actions{display:flex;justify-content:flex-end;gap:8px;margin-top:16px}.sf-auth-actions button{padding:8px 12px;border-radius:8px;border:1px solid #31506b;background:#0b2237;color:#eef6ff;cursor:pointer}.sf-auth-actions .primary{border-color:#4fd1c5;color:#4fd1c5}.sf-auth-link{margin-top:10px;color:#91a9c1;font-size:10px;cursor:pointer;text-decoration:underline}`;document.head.appendChild(s)}
function setControlLock(on){['mbo','first','second','groupMbo'].forEach(id=>{const el=$('#'+id);if(!el)return;el.disabled=!on;el.classList.toggle('master-locked',!on);const label=el.closest('label');if(label){let n=label.querySelector('.master-only-note');if(!on&&!n){n=document.createElement('span');n.className='master-only-note';n.textContent='마스터 모드에서만 수정 가능';label.appendChild(n)}else if(on&&n)n.remove()}})}
function localState(){try{return JSON.parse(localStorage.getItem(STORE)||'{}')}catch(e){return{}}}function localClosed(){try{return JSON.parse(localStorage.getItem(CLOSE_KEY)||'{}')}catch(e){return{}}}
function syncGroupMbo(){const m=$('#month')?.value||'',g=$('#groupTarget')?.value||'',input=$('#groupMbo');if(!input||!m||!g)return;const z=localState(),v=(z.gmbo||z.groupMbo||{})?.[m]?.[g];input.value=Number.isFinite(Number(v))?String(v):''}
const authHeaders=token=>{const h={Accept:'application/vnd.github+json','X-GitHub-Api-Version':'2022-11-28'};if(token)h.Authorization='Bearer '+token;return h};
async function validateToken(token){const r=await fetch('https://api.github.com/user',{headers:authHeaders(token),cache:'no-store'});if(!r.ok)throw new Error('GitHub 인증 실패 ('+r.status+')');const u=await r.json();const p=await fetch('https://api.github.com/repos/'+REPO,{headers:authHeaders(token),cache:'no-store'});if(!p.ok)throw new Error('저장소 접근 권한이 없습니다.');return u.login}
async function keyFromPin(pin,salt){const base=await crypto.subtle.importKey('raw',enc.encode(pin),'PBKDF2',false,['deriveKey']);return crypto.subtle.deriveKey({name:'PBKDF2',salt,iterations:180000,hash:'SHA-256'},base,{name:'AES-GCM',length:256},false,['encrypt','decrypt'])}
async function saveAuth(token,pin){const salt=crypto.getRandomValues(new Uint8Array(16)),iv=crypto.getRandomValues(new Uint8Array(12)),key=await keyFromPin(pin,salt),cipher=await crypto.subtle.encrypt({name:'AES-GCM',iv},key,enc.encode(token));localStorage.setItem(AUTH_KEY,JSON.stringify({v:1,salt:b64(salt),iv:b64(iv),cipher:b64(cipher)}))}
async function loadAuth(pin){const raw=localStorage.getItem(AUTH_KEY);if(!raw)throw new Error('등록된 마스터 인증정보가 없습니다.');const o=JSON.parse(raw),key=await keyFromPin(pin,unb64(o.salt));try{return dec.decode(await crypto.subtle.decrypt({name:'AES-GCM',iv:unb64(o.iv)},key,unb64(o.cipher)))}catch(e){throw new Error('PIN이 올바르지 않습니다.')}}
function modal(mode){return new Promise(resolve=>{const first=mode==='setup',wrap=document.createElement('div');wrap.className='sf-auth-modal';wrap.innerHTML=`<div class="sf-auth-box"><h3>${first?'마스터 인증 최초 등록':'마스터 모드'}</h3><p>${first?'GitHub 토큰은 최초 1회만 입력합니다. 이후에는 6자리 PIN만 사용합니다.':'등록한 6자리 PIN을 입력하세요.'}</p>${first?'<label>GitHub Fine-grained Token<input id="sfAuthToken" type="password" autocomplete="off"></label>':''}<label>6자리 PIN<input id="sfAuthPin" type="password" inputmode="numeric" maxlength="6" pattern="[0-9]{6}" autocomplete="off"></label>${first?'<label>PIN 확인<input id="sfAuthPin2" type="password" inputmode="numeric" maxlength="6" autocomplete="off"></label>':''}<div class="sf-auth-actions"><button data-cancel>취소</button><button class="primary" data-ok>${first?'등록':'확인'}</button></div>${!first?'<div class="sf-auth-link" data-reset>등록정보 초기화</div>':''}</div>`;document.body.appendChild(wrap);const pin=wrap.querySelector('#sfAuthPin');pin.focus();const close=v=>{wrap.remove();resolve(v)};wrap.querySelector('[data-cancel]').onclick=()=>close(null);wrap.querySelector('[data-ok]').onclick=()=>{const p=pin.value.trim();if(!/^\d{6}$/.test(p))return alert('PIN은 숫자 6자리로 입력해 주세요.');if(first){const p2=wrap.querySelector('#sfAuthPin2').value.trim(),t=wrap.querySelector('#sfAuthToken').value.trim();if(!t)return alert('GitHub 토큰을 입력해 주세요.');if(p!==p2)return alert('PIN 확인 값이 일치하지 않습니다.');close({pin:p,token:t})}else close({pin:p})};wrap.querySelector('[data-reset]')?.addEventListener('click',()=>{if(confirm('저장된 마스터 인증정보를 초기화할까요?')){localStorage.removeItem(AUTH_KEY);close({reset:true})}});wrap.addEventListener('keydown',e=>{if(e.key==='Enter')wrap.querySelector('[data-ok]').click();if(e.key==='Escape')close(null)})})}
function setMaster(on,login){const input=$('#upload'),label=input?.closest('.upload'),btn=$('#masterModeBtn'),badge=$('#masterBadge');if(input)input.disabled=!on;if(label)label.classList.toggle('locked',!on);setControlLock(on);if(btn){btn.classList.toggle('on',on);btn.textContent=on?'마스터 모드 종료':'마스터 모드'}if(badge){badge.classList.toggle('on',on);badge.textContent=on?`마스터 활성 · ${login||''}`:'일반 조회 모드'}window.dispatchEvent(new CustomEvent('sf-master-mode-change',{detail:{on,login:login||''}}))}
async function toggleMaster(){if(window.__sfMasterToken){window.__sfMasterToken=null;setMaster(false);syncGroupMbo();status(lastSharedDate());return}try{let token,pin,login;if(localStorage.getItem(AUTH_KEY)){const r=await modal('login');if(!r)return;if(r.reset){status('마스터 인증정보가 초기화되었습니다.');return}pin=r.pin;token=await loadAuth(pin);status('마스터 권한 확인 중...');login=await validateToken(token)}else{const r=await modal('setup');if(!r)return;pin=r.pin;token=r.token;status('마스터 권한 확인 중...');login=await validateToken(token);await saveAuth(token,pin)}window.__sfMasterToken=token;setMaster(true,login);status(lastSharedDate())}catch(e){window.__sfMasterToken=null;setMaster(false);status('마스터 인증 오류: '+e.message)}}
async function getSharedMeta(token){const r=await fetch(API+`?ref=${BRANCH}&t=${Date.now()}`,{headers:authHeaders(token),cache:'no-store'});if(!r.ok)throw new Error('공용 데이터 파일 조회 실패 ('+r.status+')');return r.json()}
async function readSharedApi(token){const h=authHeaders(token);h.Accept='application/vnd.github.raw+json';const r=await fetch(API+`?ref=${BRANCH}&t=${Date.now()}`,{headers:h,cache:'no-store'});if(!r.ok)throw new Error('공용 데이터 조회 실패 ('+r.status+')');return r.json()}window.__sfReadShared=readSharedApi;
function b64utf8(text){const bytes=enc.encode(text);let s='';for(let i=0;i<bytes.length;i+=0x8000)s+=String.fromCharCode(...bytes.subarray(i,i+0x8000));return btoa(s)}
async function readShared(){try{return await readSharedApi(window.__sfMasterToken)}catch(e){return{schemaVersion:1,uploads:[],sourceFiles:[],mbo:{},gmbo:{},sched:{},closedVendors:{}}}}const sleep=ms=>new Promise(r=>setTimeout(r,ms));
async function verifyWrite(next){let lastErr='';for(let i=0;i<8;i++){try{const got=await readSharedApi(window.__sfMasterToken);if(got?.updatedAt===next.updatedAt&&lastDateOf(got)===lastDateOf(next)){window.__sfSharedMeta=got;window.__SF_SHARED_UPLOADS=Array.isArray(got.uploads)?got.uploads:[];window.__SF_SHARED_LAST=lastDateOf(got);window.__SF_SHARED_CLOSED=got.closedVendors||{};return got}lastErr='저장 직후 데이터 버전 불일치'}catch(e){lastErr=e.message}await sleep(350+i*150)}throw new Error('GitHub 저장 검증 실패: '+lastErr)}
async function putShared(next,message){const token=window.__sfMasterToken;if(!token)throw new Error('마스터 모드가 아닙니다.');let last='';for(let attempt=0;attempt<2;attempt++){const meta=await getSharedMeta(token),latest=attempt?await readSharedApi(token):null,body=attempt&&latest?{...latest,...next,updatedAt:new Date().toISOString()}:next;const r=await fetch(API,{method:'PUT',headers:{...authHeaders(token),'Content-Type':'application/json'},body:JSON.stringify({message,content:b64utf8(JSON.stringify(body)),sha:meta.sha,branch:BRANCH})});if(r.ok)return verifyWrite(body);let msg='';try{msg=(await r.json()).message||''}catch(e){}last=`GitHub 공용 데이터 저장 실패 (${r.status}) ${msg}`;if(r.status!==409)break;await sleep(250)}throw new Error(last)}
window.__sfPublishShared=async function(payload,sourceFiles){const previous=await readShared(),months=new Set(sourceFiles.map(x=>x.month).filter(Boolean)),dates=new Set(sourceFiles.map(x=>x.date).filter(Boolean)),kept=(previous.sourceFiles||[]).filter(x=>!(x.month&&months.has(x.month))&&!dates.has(x.date));const next={...previous,schemaVersion:4,updatedAt:new Date().toISOString(),updatedBy:'master',uploads:payload.up||[],mbo:payload.mbo||previous.mbo||{},gmbo:payload.gmbo||previous.gmbo||{},sched:payload.sched||previous.sched||{},closedVendors:payload.closedVendors||previous.closedVendors||localClosed(),sourceFiles:[...kept,...sourceFiles]};return putShared(next,`Update shared sales data ${sourceFiles.map(x=>x.month||x.date).join(', ')}`)};
async function publishSettings(){if(!window.__sfMasterToken)return;let local={};try{local=JSON.parse(localStorage.getItem(STORE)||'{}')}catch(e){}const previous=await readShared(),next={...previous,schemaVersion:4,updatedAt:new Date().toISOString(),updatedBy:'master',mbo:local.mbo||previous.mbo||{},gmbo:local.gmbo||local.groupMbo||previous.gmbo||{},sched:local.sched||previous.sched||{},closedVendors:localClosed()};status('공용 설정 저장 중...');const got=await putShared(next,'Update shared MBO, product-group MBO, collection schedule and vendor close state');status(lastSharedDate());return got}window.__sfPublishSettings=publishSettings;window.__sfPublishVendorClosed=async function(){if(!window.__sfMasterToken)throw new Error('마스터 모드에서만 마감 상태를 저장할 수 있습니다.');return publishSettings()};
function install(){addStyle();const panel=$('#status')?.parentElement;if(panel&&!$('#masterModeBtn')){const bar=document.createElement('div');bar.className='master-bar';bar.innerHTML='<button type="button" id="masterModeBtn" class="master-btn">마스터 모드</button><span id="masterBadge" class="master-badge">일반 조회 모드</span>';panel.appendChild(bar);$('#masterModeBtn').onclick=toggleMaster}setMaster(false);['mbo','first','second'].forEach(id=>{const el=$('#'+id);if(el&&!el.dataset.sharedSetting){el.dataset.sharedSetting='1';el.addEventListener('change',()=>{if(!window.__sfMasterToken)return;setTimeout(()=>publishSettings().catch(e=>status('공용 설정 저장 오류: '+e.message)),60)})}})}
document.addEventListener('change',e=>{if(e.target?.id==='groupTarget'||e.target?.id==='month')syncGroupMbo()});window.addEventListener('sf-group-mbo-committed',()=>{if(!window.__sfMasterToken)return;setTimeout(()=>publishSettings().catch(e=>status('제품군 MBO 공용 저장 오류: '+e.message)),80)});install();setTimeout(syncGroupMbo,700);setTimeout(syncGroupMbo,1600);
})();