(()=>{'use strict';
const REPO='yhbae106/Sales_Forecast',PATH='shared-data/sales-history.json',BRANCH='main',RAW='https://raw.githubusercontent.com/yhbae106/Sales_Forecast/main/shared-data/sales-history.json';
const $=s=>document.querySelector(s),status=m=>{const e=$('#status');if(e)e.textContent=m};
window.__sfMasterToken=null;
function lastSharedDate(){const s=window.__sfSharedMeta||{},a=(s.sourceFiles||[]).map(x=>x.lastDate||x.date).filter(Boolean),b=(s.uploads||[]).map(x=>x.d||x.date).filter(Boolean),d=[...a,...b].sort().at(-1);return d?`${Number(d.slice(5,7))}/${Number(d.slice(8))}까지 반영 완료`:'공용 매출 데이터 연결 완료 · 마스터 업로드 대기'}
function addStyle(){if($('#sharedV31Style'))return;const s=document.createElement('style');s.id='sharedV31Style';s.textContent=`.master-bar{display:flex;gap:8px;align-items:center;flex-wrap:wrap;margin-top:10px}.master-btn{border:1px solid #31506b;background:#0b2237;color:#cfe4f4;border-radius:8px;padding:7px 10px;font-size:11px;font-weight:800;cursor:pointer}.master-btn.on{border-color:#4fd1c5;color:#4fd1c5;background:#0a2c32}.master-badge{font-size:11px;color:#91a9c1}.master-badge.on{color:#59d98e}.upload.locked{opacity:.62}.upload.locked:after{content:' · 마스터 전용';color:#ffb454;font-size:10px}`;document.head.appendChild(s)}
async function validateToken(token){const r=await fetch('https://api.github.com/user',{headers:{Accept:'application/vnd.github+json',Authorization:'Bearer '+token,'X-GitHub-Api-Version':'2022-11-28'}});if(!r.ok)throw new Error('GitHub 인증 실패 ('+r.status+')');const u=await r.json();const p=await fetch('https://api.github.com/repos/'+REPO,{headers:{Accept:'application/vnd.github+json',Authorization:'Bearer '+token,'X-GitHub-Api-Version':'2022-11-28'}});if(!p.ok)throw new Error('저장소 접근 권한이 없습니다.');return u.login}
function setMaster(on,login){const input=$('#upload'),label=input?.closest('.upload'),btn=$('#masterModeBtn'),badge=$('#masterBadge');if(input)input.disabled=!on;if(label)label.classList.toggle('locked',!on);if(btn){btn.classList.toggle('on',on);btn.textContent=on?'마스터 모드 종료':'마스터 모드'}if(badge){badge.classList.toggle('on',on);badge.textContent=on?`마스터 활성 · ${login||''}`:'일반 조회 모드'}}
async function toggleMaster(){if(window.__sfMasterToken){window.__sfMasterToken=null;setMaster(false);status(lastSharedDate());return}const token=prompt('GitHub Fine-grained Token을 입력하세요.\nSales_Forecast 저장소의 Contents: Read and write 권한이 필요합니다.\n토큰은 브라우저에 저장하지 않습니다.');if(!token)return;try{status('마스터 권한 확인 중...');const login=await validateToken(token.trim());window.__sfMasterToken=token.trim();setMaster(true,login);status(lastSharedDate())}catch(e){window.__sfMasterToken=null;setMaster(false);status('마스터 인증 오류: '+e.message)}}
function install(){addStyle();const panel=$('#status')?.parentElement;if(panel&&!$('#masterModeBtn')){const bar=document.createElement('div');bar.className='master-bar';bar.innerHTML='<button type="button" id="masterModeBtn" class="master-btn">마스터 모드</button><span id="masterBadge" class="master-badge">일반 조회 모드</span>';panel.appendChild(bar);$('#masterModeBtn').onclick=toggleMaster}setMaster(false)}
async function getSharedMeta(token){const r=await fetch(`https://api.github.com/repos/${REPO}/contents/${PATH}?ref=${BRANCH}`,{headers:{Accept:'application/vnd.github+json',Authorization:'Bearer '+token,'X-GitHub-Api-Version':'2022-11-28'},cache:'no-store'});if(!r.ok)throw new Error('공용 데이터 파일 조회 실패 ('+r.status+')');return r.json()}
function b64utf8(text){const bytes=new TextEncoder().encode(text);let s='';for(let i=0;i<bytes.length;i+=0x8000)s+=String.fromCharCode(...bytes.subarray(i,i+0x8000));return btoa(s)}
window.__sfPublishShared=async function(payload,sourceFiles){const token=window.__sfMasterToken;if(!token)throw new Error('마스터 모드가 아닙니다.');const meta=await getSharedMeta(token);let previous={schemaVersion:1,uploads:[],sourceFiles:[]};try{const rr=await fetch(RAW+'?t='+Date.now(),{cache:'no-store'});if(rr.ok)previous=await rr.json()}catch(e){}const months=new Set(sourceFiles.map(x=>x.month).filter(Boolean));const dates=new Set(sourceFiles.map(x=>x.date).filter(Boolean));const kept=(previous.sourceFiles||[]).filter(x=>!(x.month&&months.has(x.month))&&!dates.has(x.date));const next={schemaVersion:1,updatedAt:new Date().toISOString(),updatedBy:'master',uploads:payload.up||[],sourceFiles:[...kept,...sourceFiles]};const r=await fetch(`https://api.github.com/repos/${REPO}/contents/${PATH}`,{method:'PUT',headers:{Accept:'application/vnd.github+json',Authorization:'Bearer '+token,'X-GitHub-Api-Version':'2022-11-28','Content-Type':'application/json'},body:JSON.stringify({message:`Update shared sales data ${sourceFiles.map(x=>x.month||x.date).join(', ')}`,content:b64utf8(JSON.stringify(next)),sha:meta.sha,branch:BRANCH})});if(!r.ok){let msg='';try{msg=(await r.json()).message||''}catch(e){}throw new Error('GitHub 공용 데이터 저장 실패 ('+r.status+') '+msg)}window.__sfSharedMeta=next;return next};
install();
})();