(()=>{'use strict';
const REPO='yhbae106/Sales_Forecast',PATH='shared-data/sales-history.json',BRANCH='main',API=`https://api.github.com/repos/yhbae106/Sales_Forecast/contents/shared-data/sales-history.json`,STORE='sales_forecast_v16';
const $=s=>document.querySelector(s),status=m=>{const e=$('#status');if(e)e.textContent=m};
window.__sfMasterToken=null;
function lastDateOf(s){const a=(s?.sourceFiles||[]).map(x=>x.lastDate||x.date).filter(Boolean),b=(s?.uploads||[]).map(x=>x.d||x.date).filter(Boolean);return [...a,...b].sort().at(-1)||''}
function lastSharedDate(){const d=lastDateOf(window.__sfSharedMeta||{});return d?`${Number(d.slice(5,7))}/${Number(d.slice(8))}까지 반영 완료`:'공용 매출 데이터 연결 완료 · 마스터 업로드 대기'}
function addStyle(){if($('#sharedV31Style'))return;const s=document.createElement('style');s.id='sharedV31Style';s.textContent=`.master-bar{display:flex;gap:8px;align-items:center;flex-wrap:wrap;margin-top:10px}.master-btn{border:1px solid #31506b;background:#0b2237;color:#cfe4f4;border-radius:8px;padding:7px 10px;font-size:11px;font-weight:800;cursor:pointer}.master-btn.on{border-color:#4fd1c5;color:#4fd1c5;background:#0a2c32}.master-badge{font-size:11px;color:#91a9c1}.master-badge.on{color:#59d98e}.upload.locked{opacity:.62}.upload.locked:after{content:' · 마스터 전용';color:#ffb454;font-size:10px}.master-locked{opacity:.62;cursor:not-allowed}.master-only-note{display:block;margin-top:4px;font-size:9px;color:#ffb454}`;document.head.appendChild(s)}
function setControlLock(on){['mbo','first','second','groupMbo'].forEach(id=>{const el=$('#'+id);if(!el)return;el.disabled=!on;el.classList.toggle('master-locked',!on);const label=el.closest('label');if(label){let n=label.querySelector('.master-only-note');if(!on&&!n){n=document.createElement('span');n.className='master-only-note';n.textContent='마스터 모드에서만 수정 가능';label.appendChild(n)}else if(on&&n)n.remove()}})}
function localState(){try{return JSON.parse(localStorage.getItem(STORE)||'{}')}catch(e){return{}}}
function syncGroupMbo(){const m=$('#month')?.value||'',g=$('#groupTarget')?.value||'',input=$('#groupMbo');if(!input||!m||!g)return;const z=localState(),v=(z.gmbo||z.groupMbo||{})?.[m]?.[g];input.value=Number.isFinite(Number(v))?String(v):''}
const authHeaders=token=>{const h={Accept:'application/vnd.github+json','X-GitHub-Api-Version':'2022-11-28'};if(token)h.Authorization='Bearer '+token;return h};
async function validateToken(token){const r=await fetch('https://api.github.com/user',{headers:authHeaders(token),cache:'no-store'});if(!r.ok)throw new Error('GitHub 인증 실패 ('+r.status+')');const u=await r.json();const p=await fetch('https://api.github.com/repos/'+REPO,{headers:authHeaders(token),cache:'no-store'});if(!p.ok)throw new Error('저장소 접근 권한이 없습니다.');return u.login}
function setMaster(on,login){const input=$('#upload'),label=input?.closest('.upload'),btn=$('#masterModeBtn'),badge=$('#masterBadge');if(input)input.disabled=!on;if(label)label.classList.toggle('locked',!on);setControlLock(on);if(btn){btn.classList.toggle('on',on);btn.textContent=on?'마스터 모드 종료':'마스터 모드'}if(badge){badge.classList.toggle('on',on);badge.textContent=on?`마스터 활성 · ${login||''}`:'일반 조회 모드'}window.dispatchEvent(new CustomEvent('sf-master-mode-change',{detail:{on,login:login||''}}))}
async function toggleMaster(){if(window.__sfMasterToken){window.__sfMasterToken=null;setMaster(false);syncGroupMbo();status(lastSharedDate());return}const token=prompt('GitHub Fine-grained Token을 입력하세요.\nSales_Forecast 저장소의 Contents: Read and write 권한이 필요합니다.\n토큰은 브라우저에 저장하지 않습니다.');if(!token)return;try{status('마스터 권한 확인 중...');const login=await validateToken(token.trim());window.__sfMasterToken=token.trim();setMaster(true,login);status(lastSharedDate())}catch(e){window.__sfMasterToken=null;setMaster(false);status('마스터 인증 오류: '+e.message)}}
async function getSharedMeta(token){const r=await fetch(API+`?ref=${BRANCH}&t=${Date.now()}`,{headers:authHeaders(token),cache:'no-store'});if(!r.ok)throw new Error('공용 데이터 파일 조회 실패 ('+r.status+')');return r.json()}
async function readSharedApi(token){const h=authHeaders(token);h.Accept='application/vnd.github.raw+json';const r=await fetch(API+`?ref=${BRANCH}&t=${Date.now()}`,{headers:h,cache:'no-store'});if(!r.ok)throw new Error('공용 데이터 조회 실패 ('+r.status+')');return r.json()}
window.__sfReadShared=readSharedApi;
function b64utf8(text){const bytes=new TextEncoder().encode(text);let s='';for(let i=0;i<bytes.length;i+=0x8000)s+=String.fromCharCode(...bytes.subarray(i,i+0x8000));return btoa(s)}
async function readShared(){try{return await readSharedApi(window.__sfMasterToken)}catch(e){return{schemaVersion:1,uploads:[],sourceFiles:[],mbo:{},gmbo:{},sched:{}}}}
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
async function verifyWrite(next){let lastErr='';for(let i=0;i<8;i++){try{const got=await readSharedApi(window.__sfMasterToken);if(got?.updatedAt===next.updatedAt&&lastDateOf(got)===lastDateOf(next)){window.__sfSharedMeta=got;window.__SF_SHARED_UPLOADS=Array.isArray(got.uploads)?got.uploads:[];window.__SF_SHARED_LAST=lastDateOf(got);return got}lastErr='저장 직후 데이터 버전 불일치'}catch(e){lastErr=e.message}await sleep(350+i*150)}throw new Error('GitHub 저장 검증 실패: '+lastErr)}
async function putShared(next,message){const token=window.__sfMasterToken;if(!token)throw new Error('마스터 모드가 아닙니다.');const meta=await getSharedMeta(token);const r=await fetch(API,{method:'PUT',headers:{...authHeaders(token),'Content-Type':'application/json'},body:JSON.stringify({message,content:b64utf8(JSON.stringify(next)),sha:meta.sha,branch:BRANCH})});if(!r.ok){let msg='';try{msg=(await r.json()).message||''}catch(e){}throw new Error('GitHub 공용 데이터 저장 실패 ('+r.status+') '+msg)}return verifyWrite(next)}
window.__sfPublishShared=async function(payload,sourceFiles){const previous=await readShared(),months=new Set(sourceFiles.map(x=>x.month).filter(Boolean)),dates=new Set(sourceFiles.map(x=>x.date).filter(Boolean)),kept=(previous.sourceFiles||[]).filter(x=>!(x.month&&months.has(x.month))&&!dates.has(x.date));const next={...previous,schemaVersion:3,updatedAt:new Date().toISOString(),updatedBy:'master',uploads:payload.up||[],mbo:payload.mbo||previous.mbo||{},gmbo:payload.gmbo||previous.gmbo||{},sched:payload.sched||previous.sched||{},sourceFiles:[...kept,...sourceFiles]};return putShared(next,`Update shared sales data ${sourceFiles.map(x=>x.month||x.date).join(', ')}`)};
async function publishSettings(){if(!window.__sfMasterToken)return;let local={};try{local=JSON.parse(localStorage.getItem(STORE)||'{}')}catch(e){}const previous=await readShared(),next={...previous,schemaVersion:3,updatedAt:new Date().toISOString(),updatedBy:'master',mbo:local.mbo||previous.mbo||{},gmbo:local.gmbo||local.groupMbo||previous.gmbo||{},sched:local.sched||previous.sched||{}};status('공용 설정 저장 중...');const got=await putShared(next,'Update shared MBO, product-group MBO and collection schedule');status(lastSharedDate());return got}
window.__sfPublishSettings=publishSettings;
function install(){addStyle();const panel=$('#status')?.parentElement;if(panel&&!$('#masterModeBtn')){const bar=document.createElement('div');bar.className='master-bar';bar.innerHTML='<button type="button" id="masterModeBtn" class="master-btn">마스터 모드</button><span id="masterBadge" class="master-badge">일반 조회 모드</span>';panel.appendChild(bar);$('#masterModeBtn').onclick=toggleMaster}setMaster(false);['mbo','first','second'].forEach(id=>{const el=$('#'+id);if(el&&!el.dataset.sharedSetting){el.dataset.sharedSetting='1';el.addEventListener('change',()=>{if(!window.__sfMasterToken)return;setTimeout(()=>publishSettings().catch(e=>status('공용 설정 저장 오류: '+e.message)),60)})}})}
document.addEventListener('change',e=>{if(e.target?.id==='groupTarget'||e.target?.id==='month')syncGroupMbo()});
window.addEventListener('sf-group-mbo-committed',()=>{if(!window.__sfMasterToken)return;setTimeout(()=>publishSettings().catch(e=>status('제품군 MBO 공용 저장 오류: '+e.message)),80)});
install();setTimeout(syncGroupMbo,700);setTimeout(syncGroupMbo,1600);
})();