(()=>{'use strict';
const STORE='sales_forecast_v16';
const N=v=>Number(v||0);
const status=m=>{const e=document.getElementById('status');if(e)e.textContent=m};
function loadX(){if(window.XLSX)return Promise.resolve(window.XLSX);return new Promise((resolve,reject)=>{const urls=['https://cdn.jsdelivr.net/npm/xlsx@0.18.5/dist/xlsx.full.min.js','https://cdn.sheetjs.com/xlsx-0.20.3/package/dist/xlsx.full.min.js'];let i=0;const next=()=>{if(i>=urls.length)return reject(new Error('Excel 모듈 로딩 실패'));const s=document.createElement('script');s.src=urls[i++];s.async=true;s.onload=()=>resolve(window.XLSX);s.onerror=next;document.head.appendChild(s)};next()})}
function parseCellDate(v){if(v instanceof Date){const y=v.getFullYear(),m=String(v.getMonth()+1).padStart(2,'0'),d=String(v.getDate()).padStart(2,'0');return`${y}-${m}-${d}`}if(typeof v==='number'&&window.XLSX){const q=XLSX.SSF.parse_date_code(v);if(q)return`${q.y}-${String(q.m).padStart(2,'0')}-${String(q.d).padStart(2,'0')}`}const m=String(v||'').match(/(20\d{2})[.\/-](\d{1,2})[.\/-](\d{1,2})/);return m?`${m[1]}-${m[2].padStart(2,'0')}-${m[3].padStart(2,'0')}`:null}
function dateFromFilename(name){let m=String(name||'').match(/(?:^|\D)(20\d{2})(\d{2})(\d{2})(?:\D|$)/);if(m)return`${m[1]}-${m[2]}-${m[3]}`;m=String(name||'').match(/(?:^|\D)(\d{2})(\d{2})(\d{2})(?:\D|$)/);if(m)return`20${m[1]}-${m[2]}-${m[3]}`;return null}
function readStore(){try{return JSON.parse(localStorage.getItem(STORE)||localStorage.getItem('sales_forecast_v15')||'{}')}catch(e){return{}}}
function seedRows(){const raw=window.SEED_DATA?.dailyRecords||[];return raw.map(r=>({d:r.date,v:r.vendor||'',g:r.productGroup||'미분류',m:r.material||'미분류',a:N(r.amount)}))}
function key(r){return[r.v,r.g,r.m].join('\u0001')}
function baselineBefore(date,uploads){const month=date.slice(0,7),mp={};const saved=(uploads||[]).map(r=>({d:r.d||r.date,v:r.v||r.vendor||'',g:r.g||r.productGroup||'미분류',m:r.m||r.material||'미분류',a:N(r.a??r.amount)}));const replaced=new Set(saved.filter(r=>r.d<date).map(r=>r.d));const seed=seedRows().filter(r=>r.d?.slice(0,7)===month&&r.d<date&&!replaced.has(r.d));seed.concat(saved.filter(r=>r.d?.slice(0,7)===month&&r.d<date)).forEach(r=>mp[key(r)]=(mp[key(r)]||0)+N(r.a));return mp}
async function parseFile(file){await loadX();const wb=XLSX.read(await file.arrayBuffer(),{type:'array',cellDates:true}),ws=wb.Sheets[wb.SheetNames[0]],raw=XLSX.utils.sheet_to_json(ws,{defval:null,raw:true});if(!raw.length)throw new Error('업로드 파일에 데이터가 없습니다.');const dateCols=['일자','매출일자','전표일자','청구일자'];let inferred=dateFromFilename(file.name);if(!inferred){for(const r of raw){for(const c of dateCols){const d=parseCellDate(r[c]);if(d){inferred=d;break}}if(inferred)break}}
if(!inferred)throw new Error('파일에서 일자를 찾을 수 없습니다. 파일명을 260824_일자별.xlsx 형식으로 저장해 주세요.');
const snapshot={},explicitDates=new Set();let hasExplicitDate=false;raw.forEach(r=>{const v=r['판매처명'];if(!v)return;let d=null;for(const c of dateCols){d=parseCellDate(r[c]);if(d){hasExplicitDate=true;explicitDates.add(d);break}}d=d||inferred;const g=String(r['제품계층구조2 명']||'미분류'),m=String(r['자재명']||'미분류'),k=[v,g,m].join('\u0001');snapshot[k]=(snapshot[k]||0)+N(r['실매출액'])});
return{date:inferred,snapshot,hasExplicitDate,explicitDates:[...explicitDates]}}
async function handle(files){const state=readStore();state.up=state.up||state.uploadRows||state.uploads||[];let newest='';for(const file of files){const p=await parseFile(file);const d=p.date,month=d.slice(0,7);if(p.hasExplicitDate&&p.explicitDates.length>1){throw new Error('한 파일에 여러 일자가 포함되어 있습니다. 현재 형식은 누적 스냅샷 파일 1개당 기준일 1개를 권장합니다.')}const base=baselineBefore(d,state.up);const newRows=[];Object.entries(p.snapshot).forEach(([k,cum])=>{const prev=N(base[k]),delta=N(cum)-prev;if(Math.abs(delta)<0.000001)return;const [v,g,m]=k.split('\u0001');newRows.push({d,v,g,m,a:delta})});state.up=state.up.filter(r=>(r.d||r.date)!==d);state.up.push(...newRows);newest=d;const snapTotal=Object.values(p.snapshot).reduce((s,x)=>s+N(x),0),deltaTotal=newRows.reduce((s,r)=>s+N(r.a),0);status(`${file.name} 반영 완료 · ${d} 기준 누적 ${(snapTotal/1e8).toFixed(1)}억 · 당일 증분 ${(deltaTotal/1e8).toFixed(1)}억`)}
localStorage.setItem(STORE,JSON.stringify({mbo:state.mbo||{},gmbo:state.gmbo||state.groupMbo||{},sched:state.sched||{},up:state.up}));if(newest){sessionStorage.setItem('sales_forecast_prefer_date',newest);location.reload()}}
function install(){const input=document.getElementById('upload');if(!input||input.dataset.v27)return;input.dataset.v27='1';input.addEventListener('change',e=>{if(!e.target.files?.length)return;e.preventDefault();e.stopImmediatePropagation();const files=[...e.target.files];e.target.value='';handle(files).catch(err=>status('업로드 오류: '+err.message))},true)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install);else install();setTimeout(install,500);
})();