(()=>{'use strict';
const STORE='sales_forecast_v16';
const N=v=>Number(v||0);
const status=m=>{const e=document.getElementById('status');if(e)e.textContent=m};
function loadX(){if(window.XLSX)return Promise.resolve(window.XLSX);return new Promise((resolve,reject)=>{const urls=['https://cdn.jsdelivr.net/npm/xlsx@0.18.5/dist/xlsx.full.min.js','https://cdn.sheetjs.com/xlsx-0.20.3/package/dist/xlsx.full.min.js'];let i=0;const next=()=>{if(i>=urls.length)return reject(new Error('Excel 모듈 로딩 실패'));const s=document.createElement('script');s.src=urls[i++];s.async=true;s.onload=()=>resolve(window.XLSX);s.onerror=next;document.head.appendChild(s)};next()})}
function fileDate(name){const s=String(name||'');let m=s.match(/(?:^|\D)(20\d{2})(\d{2})(\d{2})(?:\D|$)/);if(m)return`${m[1]}-${m[2]}-${m[3]}`;m=s.match(/(?:^|\D)(\d{2})(\d{2})(\d{2})(?:\D|$)/);return m?`20${m[1]}-${m[2]}-${m[3]}`:null}
function cellDate(v){if(v instanceof Date){const y=v.getFullYear(),m=String(v.getMonth()+1).padStart(2,'0'),d=String(v.getDate()).padStart(2,'0');return`${y}-${m}-${d}`}if(typeof v==='number'&&window.XLSX){const q=XLSX.SSF.parse_date_code(v);if(q)return`${q.y}-${String(q.m).padStart(2,'0')}-${String(q.d).padStart(2,'0')}`}const m=String(v||'').match(/(20\d{2})[.\/-](\d{1,2})[.\/-](\d{1,2})/);return m?`${m[1]}-${m[2].padStart(2,'0')}-${m[3].padStart(2,'0')}`:null}
function state(){try{const z=JSON.parse(localStorage.getItem(STORE)||localStorage.getItem('sales_forecast_v15')||'{}');z.up=z.up||z.uploadRows||z.uploads||[];return z}catch(e){return{up:[],mbo:{},gmbo:{},sched:{}}}}
function seed(){return(window.SEED_DATA?.dailyRecords||[]).map(r=>({d:r.date,v:r.vendor||'',g:r.productGroup||'미분류',m:r.material||'미분류',a:N(r.amount)}))}
const K=r=>[r.v,r.g,r.m].join('\u0001');
function baseBefore(date,up){const mo=date.slice(0,7),saved=(up||[]).map(r=>({d:r.d||r.date,v:r.v||r.vendor||'',g:r.g||r.productGroup||'미분류',m:r.m||r.material||'미분류',a:N(r.a??r.amount)})),replaced=new Set(saved.filter(r=>r.d<date).map(r=>r.d)),mp={};seed().filter(r=>r.d?.slice(0,7)===mo&&r.d<date&&!replaced.has(r.d)).concat(saved.filter(r=>r.d?.slice(0,7)===mo&&r.d<date)).forEach(r=>mp[K(r)]=(mp[K(r)]||0)+N(r.a));return mp}
async function parse(file){await loadX();const wb=XLSX.read(await file.arrayBuffer(),{type:'array',cellDates:true}),ws=wb.Sheets[wb.SheetNames[0]],raw=XLSX.utils.sheet_to_json(ws,{defval:null,raw:true});if(!raw.length)throw new Error('업로드 파일에 데이터가 없습니다.');let d=fileDate(file.name);const dateCols=['일자','매출일자','전표일자','청구일자'];if(!d){for(const r of raw){for(const c of dateCols){d=cellDate(r[c]);if(d)break}if(d)break}}if(!d)throw new Error('기준일을 찾지 못했습니다. 파일명을 260824_일자별.xlsx 형태로 저장해 주세요.');const fileMonth=String(raw[0]['년월']||'').replace('.','-');if(fileMonth&&/^20\d{2}-\d{2}$/.test(fileMonth)&&d.slice(0,7)!==fileMonth)throw new Error(`파일명 날짜(${d})와 년월(${fileMonth})이 일치하지 않습니다.`);const snap={};for(const r of raw){const v=String(r['판매처명']||'').trim();if(!v)continue;const g=String(r['제품계층구조2 명']||'미분류').trim()||'미분류',m=String(r['자재명']||'미분류').trim()||'미분류',k=[v,g,m].join('\u0001');snap[k]=(snap[k]||0)+N(r['실매출액'])}return{date:d,snap}}
async function handle(files){const st=state();let newest='';for(const f of files){status(`${f.name} 읽는 중...`);const {date,snap}=await parse(f),base=baseBefore(date,st.up),rows=[];const keys=new Set([...Object.keys(base),...Object.keys(snap)]);for(const k of keys){const delta=N(snap[k])-N(base[k]);if(Math.abs(delta)<0.000001)continue;const[v,g,m]=k.split('\u0001');rows.push({d:date,v,g,m,a:delta})}st.up=st.up.filter(r=>(r.d||r.date)!==date);st.up.push(...rows);newest=date;const snapTotal=Object.values(snap).reduce((s,v)=>s+N(v),0),deltaTotal=rows.reduce((s,r)=>s+N(r.a),0);status(`${f.name} 반영 완료 · ${date} 기준 누적 ${(snapTotal/1e8).toFixed(1)}억 · 증분 ${(deltaTotal/1e8).toFixed(1)}억`)}localStorage.setItem(STORE,JSON.stringify({mbo:st.mbo||{},gmbo:st.gmbo||st.groupMbo||{},sched:st.sched||{},up:st.up}));if(newest){sessionStorage.setItem('sales_forecast_last_upload_date',newest);location.reload()}}
function install(){const input=document.getElementById('upload');if(!input)return;input.dataset.uploadHandler='v28';input.onchange=async function(){const files=[...this.files];this.value='';if(!files.length)return;try{await handle(files)}catch(e){status('업로드 오류: '+e.message)}};status('일자별 EXPORT 업로드 준비 완료 · 파일명 날짜 자동 인식 지원')}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install,{once:true});else install();setTimeout(install,300);
})();