(()=>{'use strict';
const STORE='sales_forecast_v16',N=v=>Number(String(v??0).replace(/,/g,''))||0,status=m=>{const e=document.getElementById('status');if(e)e.textContent=m};
function loadX(){if(window.XLSX)return Promise.resolve(window.XLSX);return new Promise((resolve,reject)=>{const urls=['https://cdn.jsdelivr.net/npm/xlsx@0.18.5/dist/xlsx.full.min.js','https://cdn.sheetjs.com/xlsx-0.20.3/package/dist/xlsx.full.min.js'];let i=0;const next=()=>{if(i>=urls.length)return reject(new Error('Excel 모듈 로딩 실패'));const s=document.createElement('script');s.src=urls[i++];s.async=true;s.onload=()=>resolve(window.XLSX);s.onerror=next;document.head.appendChild(s)};next()})}
function readStore(){try{return JSON.parse(localStorage.getItem(STORE)||localStorage.getItem('sales_forecast_v15')||'{}')}catch(e){return{}}}
function dateFromFilename(name){let m=String(name||'').match(/(?:^|\D)(20\d{2})(\d{2})(\d{2})(?:\D|$)/);if(m)return`${m[1]}-${m[2]}-${m[3]}`;m=String(name||'').match(/(?:^|\D)(\d{2})(\d{2})(\d{2})(?:\D|$)/);return m?`20${m[1]}-${m[2]}-${m[3]}`:null}
function dateValue(v){const s=String(v??'').trim();let m=s.match(/^(20\d{2})[.\/-](\d{1,2})[.\/-](\d{1,2})(?:\s.*)?$/);if(m)return`${m[1]}-${m[2].padStart(2,'0')}-${m[3].padStart(2,'0')}`;m=s.match(/^(20\d{2})(\d{2})(\d{2})$/);if(m)return`${m[1]}-${m[2]}-${m[3]}`;if(v instanceof Date)return`${v.getFullYear()}-${String(v.getMonth()+1).padStart(2,'0')}-${String(v.getDate()).padStart(2,'0')}`;if(typeof v==='number'&&window.XLSX&&v>20000&&v<80000){const q=XLSX.SSF.parse_date_code(v);if(q)return`${q.y}-${String(q.m).padStart(2,'0')}-${String(q.d).padStart(2,'0')}`}return null}
async function parse(file){await loadX();const wb=XLSX.read(await file.arrayBuffer(),{type:'array',cellDates:true}),ws=wb.Sheets[wb.SheetNames[0]],raw=XLSX.utils.sheet_to_json(ws,{defval:null,raw:true}),txt=XLSX.utils.sheet_to_json(ws,{defval:null,raw:false,dateNF:'yyyy-mm-dd'});if(!raw.length)throw new Error('업로드 파일에 데이터가 없습니다.');const mp={},dates=new Set(),months=new Set();let valid=0;raw.forEach((r,i)=>{const shown=txt[i]||{},d=dateValue(shown['일자'])||dateValue(r['일자']),v=String(r['판매처명']||shown['판매처명']||'').trim();if(!d||!v)return;const g=String(r['제품계층구조2 명']||shown['제품계층구조2 명']||'미분류').trim(),m=String(r['자재명']||shown['자재명']||'미분류').trim(),a=N(r['실매출액']??shown['실매출액']);dates.add(d);months.add(d.slice(0,7));const k=[d,v,g,m].join('\u0001');mp[k]=(mp[k]||0)+a;valid++});if(!valid)throw new Error('일자/판매처명/실매출액 데이터를 찾지 못했습니다.');const detected=[...months].sort(),fileDate=dateFromFilename(file.name),fileMonth=fileDate?.slice(0,7);if(months.size!==1)throw new Error(`날짜 해석 오류: 감지된 월 ${detected.join(', ')}. 파일명 기준 ${fileMonth||'확인 불가'}`);const month=detected[0];if(fileMonth&&fileMonth!==month)throw new Error(`파일명은 ${fileMonth}인데 일자 데이터는 ${month}로 확인됩니다.`);const rows=Object.entries(mp).map(([k,a])=>{const[d,v,g,m]=k.split('\u0001');return{d,v,g,m,a}}),sorted=[...dates].sort(),total=rows.reduce((s,r)=>s+N(r.a),0);return{rows,month,first:sorted[0],last:sorted.at(-1),total,dateCount:sorted.length}}
async function handle(files){if(!window.__sfMasterToken)throw new Error('마스터 모드에서만 업로드할 수 있습니다.');if(typeof window.__sfPublishShared!=='function')throw new Error('공용 데이터 연결이 준비되지 않았습니다.');const state=readStore();state.up=state.up||state.uploadRows||state.uploads||[];let newest='',sources=[];for(const file of files){status(`${file.name} 일자별 데이터 분석 중...`);const p=await parse(file);state.up=state.up.filter(r=>(r.d||r.date||'').slice(0,7)!==p.month);state.up.push(...p.rows);newest=p.last;sources.push({month:p.month,date:p.last,firstDate:p.first,lastDate:p.last,dateCount:p.dateCount,fileName:file.name,total:p.total});status(`${file.name} 처리 완료 · ${p.first}~${p.last} · ${p.dateCount}개 일자 · 누적 ${(p.total/1e8).toFixed(1)}억 · GitHub 저장 중...`)}const payload={mbo:state.mbo||{},gmbo:state.gmbo||state.groupMbo||{},sched:state.sched||{},up:state.up};await window.__sfPublishShared(payload,sources);localStorage.setItem(STORE,JSON.stringify(payload));sessionStorage.setItem('sales_forecast_prefer_date',newest);status(`공용 반영 완료 · ${newest} 기준 · 다른 브라우저에서도 동일 데이터 조회 가능`);setTimeout(()=>location.reload(),700)}
function install(){const old=document.getElementById('upload');if(!old)return;const input=old.cloneNode(true);old.replaceWith(input);input.disabled=!window.__sfMasterToken;input.addEventListener('change',e=>{if(!e.target.files?.length)return;const files=[...e.target.files];e.target.value='';handle(files).catch(err=>status('업로드 오류: '+err.message))},true);window.addEventListener('sf-master-change',e=>{input.disabled=!e.detail?.active})}
install();
})();