(()=>{'use strict';
const STORE='sales_forecast_v16',N=v=>Number(v||0),status=m=>{const e=document.getElementById('status');if(e)e.textContent=m};
function loadX(){if(window.XLSX)return Promise.resolve(window.XLSX);return new Promise((resolve,reject)=>{const urls=['https://cdn.jsdelivr.net/npm/xlsx@0.18.5/dist/xlsx.full.min.js','https://cdn.sheetjs.com/xlsx-0.20.3/package/dist/xlsx.full.min.js'];let i=0;const next=()=>{if(i>=urls.length)return reject(new Error('Excel 모듈 로딩 실패'));const s=document.createElement('script');s.src=urls[i++];s.async=true;s.onload=()=>resolve(window.XLSX);s.onerror=next;document.head.appendChild(s)};next()})}
function ensureSeed(){if(window.SEED_DATA?.dailyRecords?.length)return Promise.resolve();return new Promise((resolve,reject)=>{status('기존 일자별 기준 데이터 확인 중...');const s=document.createElement('script');s.src='data.js?masterseed=31';s.async=true;s.onload=()=>window.SEED_DATA?.dailyRecords?.length?resolve():reject(new Error('기준 일자별 데이터를 불러오지 못했습니다.'));s.onerror=()=>reject(new Error('기준 일자별 데이터 파일 로딩 실패'));document.body.appendChild(s)})}
function dateFromFilename(name){let m=String(name||'').match(/(?:^|\D)(20\d{2})(\d{2})(\d{2})(?:\D|$)/);if(m)return`${m[1]}-${m[2]}-${m[3]}`;m=String(name||'').match(/(?:^|\D)(\d{2})(\d{2})(\d{2})(?:\D|$)/);return m?`20${m[1]}-${m[2]}-${m[3]}`:null}
function readStore(){try{return JSON.parse(localStorage.getItem(STORE)||localStorage.getItem('sales_forecast_v15')||'{}')}catch(e){return{}}}
function seedRows(){return(window.SEED_DATA?.dailyRecords||[]).map(r=>({d:r.date,v:r.vendor||'',g:r.productGroup||'미분류',m:r.material||'미분류',a:N(r.amount)}))}
const K=r=>[r.v,r.g,r.m].join('\u0001');
function priorMonthSnapshot(date,state){const month=date.slice(0,7),saved=(state.up||state.uploadRows||state.uploads||[]).map(r=>({d:r.d||r.date,v:r.v||r.vendor||'',g:r.g||r.productGroup||'미분류',m:r.m||r.material||'미분류',a:N(r.a??r.amount)})),replaced=new Set(saved.filter(r=>r.d<date).map(r=>r.d)),mp={};seedRows().filter(r=>r.d?.slice(0,7)===month&&r.d<date&&!replaced.has(r.d)).concat(saved.filter(r=>r.d?.slice(0,7)===month&&r.d<date)).forEach(r=>mp[K(r)]=(mp[K(r)]||0)+N(r.a));return mp}
async function parse(file){await loadX();const wb=XLSX.read(await file.arrayBuffer(),{type:'array',cellDates:true}),ws=wb.Sheets[wb.SheetNames[0]],raw=XLSX.utils.sheet_to_json(ws,{defval:null,raw:true});if(!raw.length)throw new Error('업로드 파일에 데이터가 없습니다.');let d=dateFromFilename(file.name);if(!d){const candidates=raw.map(r=>r['일자']).filter(Boolean);if(candidates.length){const v=candidates[0];if(v instanceof Date)d=v.toISOString().slice(0,10);else{const m=String(v).match(/(20\d{2})[.\/-](\d{1,2})[.\/-](\d{1,2})/);if(m)d=`${m[1]}-${m[2].padStart(2,'0')}-${m[3].padStart(2,'0')}`}}}if(!d)throw new Error('파일명 또는 일자 컬럼에서 기준일을 찾을 수 없습니다.');const snap={};raw.forEach(r=>{const v=r['판매처명'];if(!v)return;const g=String(r['제품계층구조2 명']||'미분류'),m=String(r['자재명']||'미분류'),k=[String(v),g,m].join('\u0001');snap[k]=(snap[k]||0)+N(r['실매출액'])});return{d,snap}}
async function handle(files){if(!window.__sfMasterToken)throw new Error('마스터 모드에서만 업로드할 수 있습니다.');if(typeof window.__sfPublishShared!=='function')throw new Error('공용 데이터 연결이 준비되지 않았습니다.');await ensureSeed();const state=readStore();state.up=state.up||state.uploadRows||state.uploads||[];let newest='',sources=[];for(const file of files){status(`${file.name} 분석 중...`);const {d,snap}=await parse(file),base=priorMonthSnapshot(d,state),keys=new Set([...Object.keys(base),...Object.keys(snap)]),delta=[];keys.forEach(k=>{const a=N(snap[k])-N(base[k]);if(Math.abs(a)<1e-8)return;const[v,g,m]=k.split('\u0001');delta.push({d,v,g,m,a})});state.up=state.up.filter(r=>(r.d||r.date)!==d);state.up.push(...delta);newest=d;sources.push({date:d,fileName:file.name,total:Object.values(snap).reduce((s,a)=>s+N(a),0)});status(`${file.name} 처리 완료 · GitHub 공용 데이터 저장 중...`)}const payload={mbo:state.mbo||{},gmbo:state.gmbo||state.groupMbo||{},sched:state.sched||{},up:state.up};await window.__sfPublishShared(payload,sources);localStorage.setItem(STORE,JSON.stringify(payload));sessionStorage.setItem('sales_forecast_prefer_date',newest);status(`공용 반영 완료 · ${newest} · 다른 브라우저에서도 동일 데이터 조회 가능`);setTimeout(()=>location.reload(),500)}
function install(){const input=document.getElementById('upload');if(!input||input.dataset.v31)return;input.dataset.v31='1';input.onchange=null;input.addEventListener('change',e=>{if(!e.target.files?.length)return;e.preventDefault();e.stopImmediatePropagation();const files=[...e.target.files];e.target.value='';handle(files).catch(err=>status('업로드 오류: '+err.message))},true)}
install();
})();